"""flow feed score

Revision ID: 0848784862f8
Revises: 5871b5984517
Create Date: 2025-07-29 20:38:05.452592

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0848784862f8"
down_revision: str | None = "5871b5984517"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flow_feed_score_group_type",
        "group_type",
        existing_type=sa.Enum(
            "COMMUNITY",
            "INTENDED_EDUCATION",
            "INTENDED_COURSE",
            "INSTITUTION",
            "INSTITUTION_TYPE",
            "STAGE",
            "COURSE",
            name="flowfeedscoregrouptypeenum",
            native_enum=False,
            create_constraint=True,
            length=50,
        ),
        type_=sa.Enum(
            "COMMUNITY",
            "INTENDED_EDUCATION",
            "INTENDED_COURSE",
            "INSTITUTION",
            "EDUCATION_LEVEL",
            "STAGE",
            "COURSE",
            name="flowfeedscoregrouptypeenum",
            native_enum=False,
            create_constraint=True,
            length=50,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
