"""set null on ed info institution

Revision ID: 4e5519e37b65
Revises: 64e9b75604a9
Create Date: 2025-09-10 13:06:06.201989

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e5519e37b65"
down_revision: str | None = "64e9b75604a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__education_info__institution_id__institution"),
        "education_info",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__education_info__institution_id__institution"),
        "education_info",
        "institution",
        ["institution_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__education_info__institution_id__institution"),
        "education_info",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__education_info__institution_id__institution"),
        "education_info",
        "institution",
        ["institution_id"],
        ["id"],
    )
    # ### end Alembic commands ###
