"""cascade answer when delete choice

Revision ID: c8a8f58b07f7
Revises: 4e5519e37b65
Create Date: 2025-09-11 18:48:20.930024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8a8f58b07f7"
down_revision: str | None = "4e5519e37b65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__flow_question_user__choice_id__choice"),
        "flow_question_user",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__flow_question_user__choice_id__choice"),
        "flow_question_user",
        "choice",
        ["choice_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__flow_question_user__choice_id__choice"),
        "flow_question_user",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__flow_question_user__choice_id__choice"),
        "flow_question_user",
        "choice",
        ["choice_id"],
        ["id"],
    )
    # ### end Alembic commands ###
