"""changing name field

Revision ID: f768ee9f2fae
Revises: 25e6ace28f32
Create Date: 2025-06-13 16:37:02.887933

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f768ee9f2fae"
down_revision: str | None = "25e6ace28f32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("course", "name", new_column_name="name_i18n")
    op.alter_column("education_level", "name", new_column_name="name_i18n")
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("course", "name_i18n", new_column_name="name")
    op.alter_column("education_level", "name_i18n", new_column_name="name")
    # ### end Alembic commands ###
