# Generated by Django 5.1.2 on 2024-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_events', '0001_initial'),
        ('challenges', '0004_challenge_questions_per_day_challenge_scoring_system'),
        ('quiz', '0027_remove_userquizanswer_choice_xor_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusevent',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='bonusevent',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='quiz.quiz'),
        ),
    ]
