# Generated by Django 5.1.2 on 2024-12-22 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bonus_events", "0003_remove_bonusevent_quizzes_bonusevent_sessions"),
        ("quiz", "0030_migrate_quiz_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bonusevent",
            name="quizzes",
        ),
    ]
