# Generated by Django 5.0.3 on 2024-03-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_choice_question_quiz_delete_examquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
