# Generated by Django 5.0.3 on 2024-03-16 14:09

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_quiz_options_alter_question_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='question_embedding_index',
        ),
        migrations.AddIndex(
            model_name='question',
            index=pgvector.django.HnswIndex(ef_construction=200, fields=['embedding'], m=16, name='question_embedding_index', opclasses=['vector_cosine_ops']),
        ),
    ]
