# Generated by Django 5.0.4 on 2024-05-02 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userquizanswer_timestamp_userquiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_set', to='core.quiz'),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
