# Generated by Django 5.0.6 on 2024-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quiz_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='source_filter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
