# Generated by Django 5.0.6 on 2024-05-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_quiz_source_filter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='unique_query_area',
        ),
    ]
