# Generated by Django 5.0.6 on 2024-06-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_essaytopic'),
        ('essays', '0003_essay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='essay',
            name='essay_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='essays.essaytopic'),
        ),
    ]
