# Generated by Django 5.0.6 on 2024-06-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_essay_author_alter_essay_essay_topic"),
        ("essays", "0004_auto_20240611_0918"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Essay",
        ),
    ]
