[pytest]
addopts = --show-capture=stdout --capture=tee-sys
pythonpath = .
testpaths = tests
filterwarnings = 
    ignore:.*SWIG.*__module__.*:DeprecationWarning
    ignore:.*SwigPyObject.*__module__.*:DeprecationWarning
    ignore:.*SwigPyPacked.*__module__.*:DeprecationWarning
    ignore:.*swigvarlink.*__module__.*:DeprecationWarning
    ignore:Converter 'uuid' is already registered.*:django.utils.deprecation.RemovedInDjango60Warning
    ignore:Support for class-based `config` is deprecated.*:pydantic.warnings.PydanticDeprecatedSince20

