# Generated by Django 5.0.3 on 2024-03-08 16:26

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedfile',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='embeddedtextchunk',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
