# Generated by Django 5.0.3 on 2024-03-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_embeddedfile_text_alter_embeddedtextchunk_embedding"),
        ("core", "0006_essaytopic_essay"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="essay_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="core.essaytopic",
            ),
        ),
    ]
