# Generated by Django 5.0.3 on 2024-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_embeddedfile_text_alter_embeddedtextchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='chatroom_icons'),
        ),
    ]
