# Generated by Django 5.0.6 on 2024-06-11 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_school'),
        ('essays', '0002_auto_20240610_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='essay_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='essays.essaytopic'),
        ),
    ]
