# Generated by Django 5.0.6 on 2024-06-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_message_essay_topic'),
        ('quiz', '0007_auto_20240612_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='quiz.quiz'),
        ),
    ]
