# Generated by Django 5.1.6 on 2025-03-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='inep_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
