# Generated by Django 5.1.6 on 2025-03-04 20:24

from django.db import migrations, models, transaction


def collapse_same_college_courses(apps, schema_editor):
    College = apps.get_model("api", "College")
    Course = apps.get_model("api", "Course")
    User = apps.get_model("api", "User")

    def normalize(name):
        return name.strip().lower()

    with transaction.atomic():
        # --- Merge Courses ---
        # Gather courses by normalized name
        courses_by_name = {}
        for course in Course.objects.all().order_by("user_submitted", "id"):
            key = normalize(course.name)
            if key in courses_by_name:
                canonical_course = courses_by_name[key]
                # If current course is not user submitted but canonical is, swap them
                if not course.user_submitted and canonical_course.user_submitted:
                    course, canonical_course = canonical_course, course
                    courses_by_name[key] = canonical_course

                # Update foreign keys on User
                User.objects.filter(chosen_course=course).update(
                    chosen_course=canonical_course
                )

                # For each College that is related to this course, add the canonical course.
                # Using add() will not duplicate if the canonical course is already present.
                for college in course.college_set.all():
                    college.courses.add(canonical_course)
                    # Optionally, remove the duplicate course if needed:
                    college.courses.remove(course)

                # Delete the duplicate course
                course.delete()
            else:
                courses_by_name[key] = course

        # --- Merge Colleges ---
        colleges_by_name = {}
        for college in College.objects.all().order_by("user_submitted", "id"):
            key = normalize(college.name)
            if key in colleges_by_name:
                canonical_college = colleges_by_name[key]
                # If current college is not user submitted but canonical is, swap them
                if not college.user_submitted and canonical_college.user_submitted:
                    college, canonical_college = canonical_college, college
                    colleges_by_name[key] = canonical_college

                # Update foreign keys on User
                User.objects.filter(chosen_college=college).update(
                    chosen_college=canonical_college
                )

                # Merge Many-to-Many relationships:
                # Use set union to avoid duplicates. First, get all course IDs.
                current_course_ids = set(
                    canonical_college.courses.values_list("id", flat=True)
                )
                duplicate_course_ids = set(college.courses.values_list("id", flat=True))
                all_course_ids = current_course_ids.union(duplicate_course_ids)
                canonical_college.courses.set(list(all_course_ids))

                # Delete the duplicate college
                college.delete()
            else:
                colleges_by_name[key] = college


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_school_inep_code"),
    ]

    operations = [
        migrations.RunSQL(
            "SET CONSTRAINTS ALL IMMEDIATE", reverse_sql="SET CONSTRAINTS ALL DEFERRED"
        ),  # i was getting psycopg.errors.ObjectInUse: cannot ALTER TABLE "api_college" because it has pending trigger events
        migrations.RunPython(
            code=collapse_same_college_courses,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="college",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_college_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_course_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(
                condition=models.Q(("inep_code", ""), _negated=True),
                fields=("inep_code",),
                name="unique_inep_code",
            ),
        ),
        migrations.RunSQL(
            "SET CONSTRAINTS ALL DEFERRED", reverse_sql="SET CONSTRAINTS ALL IMMEDIATE"
        ),
    ]
