# Generated by Django 5.1.7 on 2025-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(blank=True, choices=[('referral', 'Amigo ou colega'), ('social', 'Redes sociais'), ('internet', 'Pesquisa na internet'), ('teacher', 'Indicação de professor'), ('event', 'Evento educacional'), ('other', 'Outro'), ('', 'Desconhecido')], default='', max_length=255),
        ),
    ]
