# Generated by Django 5.0.6 on 2024-06-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("essays", "0003_essay"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO essays_essay (
                id,
                original_file,
                extracted_text1,
                extracted_text2,
                cleaned_text,
                user_corrected_text,
                feedback1,
                feedback2,
                feedback3,
                feedback4,
                feedback5,
                created_at,
                essay_topic_id,
                author_id,
                grade1,
                grade2,
                grade3,
                grade4,
                grade5
            )
            SELECT
                id,
                original_file,
                extracted_text1,
                extracted_text2,
                cleaned_text,
                user_corrected_text,
                feedback1,
                feedback2,
                feedback3,
                feedback4,
                feedback5,
                created_at,
                essay_topic_id,
                author_id,
                grade1,
                grade2,
                grade3,
                grade4,
                grade5
            FROM
                core_essay;
            SELECT setval(pg_get_serial_sequence('"essays_essay"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "essays_essay";
            """,
            reverse_sql="""
            INSERT INTO core_essay (
                id,
                original_file,
                extracted_text1,
                extracted_text2,
                cleaned_text,
                user_corrected_text,
                feedback1,
                feedback2,
                feedback3,
                feedback4,
                feedback5,
                created_at,
                essay_topic_id,
                author_id,
                grade1,
                grade2,
                grade3,
                grade4,
                grade5
            )
            SELECT
                id,
                original_file,
                extracted_text1,
                extracted_text2,
                cleaned_text,
                user_corrected_text,
                feedback1,
                feedback2,
                feedback3,
                feedback4,
                feedback5,
                created_at,
                essay_topic_id,
                author_id,
                grade1,
                grade2,
                grade3,
                grade4,
                grade5
            FROM
                essays_essay;
            SELECT setval(pg_get_serial_sequence('"core_essay"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_essay";
            """,
        ),
    ]
