# Generated by Django 5.0.3 on 2024-03-13 22:47

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExamQuestion",
            new_name="Question",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="questions"),
        ),
        migrations.RenameField(
            model_name="question", old_name="answer", new_name="answer_text"
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_image",
            field=models.ImageField(blank=True, null=True, upload_to="answers"),
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_embedding_index",
        ),
        migrations.AddIndex(
            model_name="question",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"],
                lists=50,
                name="question_embedding_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(related_name="quizzes", to="core.question"),
        ),
    ]
