# Generated by Django 5.0.3 on 2024-03-23 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_essaytopic_essay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='essay',
            name='cleaned_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='extracted_text1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='extracted_text2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='feedback1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='feedback2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='feedback3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='feedback4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='feedback5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='essays/files/'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='user_corrected_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='essaytopic',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
