# Generated by Django 5.0.4 on 2024-04-20 01:02

import sortedm2m.fields
from django.db import migrations
from sortedm2m.operations import AlterSortedManyToManyField  # added this


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_quiz_unique_query_subject_and_more"),
    ]

    operations = [
        AlterSortedManyToManyField(  # changed this line
            model_name="quiz",
            name="questions",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, related_name="quizzes", to="core.question"
            ),
        ),
    ]
