# Generated by Django 5.0.6 on 2024-05-31 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_quiz_unique_query_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_answer_set', to='core.choice'),
        ),
        migrations.AlterField(
            model_name='userquizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_answer_set', to='core.question'),
        ),
        migrations.AlterField(
            model_name='userquizanswer',
            name='user_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_answer_set', to='core.userquiz'),
        ),
    ]
