# Generated by Django 5.0.6 on 2024-06-11 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userquizanswer_choice_and_more'),
        ('essays', '0002_auto_20240610_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essay_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='essays.essaytopic'),
        ),
    ]
