# Generated by Django 5.1.5 on 2025-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('currency', '0003_rename_amount_currency_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='valid_currency_category',
        ),
        migrations.AlterField(
            model_name='currency',
            name='category',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('essay', 'Essay'), ('duel', 'Duel'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['quiz', 'essay', 'duel', 'challenge'])), name='valid_currency_category'),
        ),
    ]
