# Generated by Django 5.0.6 on 2024-06-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0022_alter_userquizanswer_choice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayTopic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "essay topics",
            },
        ),
    ]
