# Generated by Django 5.0.6 on 2024-06-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_auto_20240610_2134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='essays/files/')),
                ('extracted_text1', models.TextField(blank=True, default='')),
                ('extracted_text2', models.TextField(blank=True, default='')),
                ('cleaned_text', models.TextField(blank=True, default='')),
                ('user_corrected_text', models.TextField(blank=True, default='')),
                ('feedback1', models.TextField(blank=True, default='')),
                ('feedback2', models.TextField(blank=True, default='')),
                ('feedback3', models.TextField(blank=True, default='')),
                ('feedback4', models.TextField(blank=True, default='')),
                ('feedback5', models.TextField(blank=True, default='')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to=settings.AUTH_USER_MODEL)),
                ('essay_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='essays.essaytopic')),
            ],
        ),
    ]
