# Generated by Django 5.1 on 2024-09-03 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models
from django.db.models import Count
from essays.constants import (
    FEEDBACK1_SYSTEM_MESSAGE,
    FEEDBACK2_SYSTEM_MESSAGE,
    FEEDBACK3_SYSTEM_MESSAGE,
    FEEDBACK4_SYSTEM_MESSAGE,
    FEEDBACK5_SYSTEM_MESSAGE,
    FEEDBACK_TEMPERATURES,
)

TEXTRACT_EXTRACTION_METHOD = "Amazon Textract"

PEN_TO_PRINT_EXTRACTION_METHOD = "Pen to Print"

ENEM_ESSAY_TYPE_NAME = "Enem"

ENEM_FEEDBACK_CATEGORIES = [
    {
        "name": "Competência 1",
        "prompt_template": FEEDBACK1_SYSTEM_MESSAGE,
        "temperature": FEEDBACK_TEMPERATURES[0],
    },
    {
        "name": "Competência 2",
        "prompt_template": FEEDBACK2_SYSTEM_MESSAGE,
        "temperature": FEEDBACK_TEMPERATURES[1],
    },
    {
        "name": "Competência 3",
        "prompt_template": FEEDBACK3_SYSTEM_MESSAGE,
        "temperature": FEEDBACK_TEMPERATURES[2],
    },
    {
        "name": "Competência 4",
        "prompt_template": FEEDBACK4_SYSTEM_MESSAGE,
        "temperature": FEEDBACK_TEMPERATURES[3],
    },
    {
        "name": "Competência 5",
        "prompt_template": FEEDBACK5_SYSTEM_MESSAGE,
        "temperature": FEEDBACK_TEMPERATURES[4],
    },
]


def create_enem_essay_type(apps, schema_editor):
    EssayType = apps.get_model("essays", "EssayType")
    EssayType.objects.create(name=ENEM_ESSAY_TYPE_NAME)


def reverse_create_enem_essay_type(apps, schema_editor):
    EssayType = apps.get_model("essays", "EssayType")
    enem_essay_type = EssayType.objects.filter(name=ENEM_ESSAY_TYPE_NAME).first()
    if enem_essay_type:
        enem_essay_type.delete()


def create_enem_feedback_categories(apps, schema_editor):
    EssayType = apps.get_model("essays", "EssayType")
    FeedbackCategory = apps.get_model("essays", "FeedbackCategory")
    enem_essay_type = EssayType.objects.filter(name=ENEM_ESSAY_TYPE_NAME).first()
    if enem_essay_type:
        for category in ENEM_FEEDBACK_CATEGORIES:
            FeedbackCategory.objects.create(
                essay_type=enem_essay_type,
                name=category["name"],
                prompt_template=category["prompt_template"],
                temperature=category["temperature"],
            )


def reverse_create_enem_feedback_categories(apps, schema_editor):
    FeedbackCategory = apps.get_model("essays", "FeedbackCategory")
    EssayType = apps.get_model("essays", "EssayType")
    enem_essay_type = EssayType.objects.filter(name=ENEM_ESSAY_TYPE_NAME).first()
    if enem_essay_type:
        FeedbackCategory.objects.filter(essay_type=enem_essay_type).delete()


def delete_null_author(apps, schema_editor):
    Essay = apps.get_model("essays", "Essay")
    Essay.objects.filter(author__isnull=True).delete()


def create_existing_extracted_texts(apps, schema_editor):
    Essay = apps.get_model("essays", "Essay")
    ExtractedText = apps.get_model("essays", "ExtractedText")
    for essay in Essay.objects.all():
        for i in range(1, 3):
            extracted_text = getattr(essay, f"extracted_text{i}")
            if extracted_text:
                ExtractedText.objects.create(
                    essay=essay,
                    text=extracted_text,
                    extraction_method=(
                        TEXTRACT_EXTRACTION_METHOD
                        if i == 1
                        else PEN_TO_PRINT_EXTRACTION_METHOD
                    ),
                )


def reverse_create_existing_extracted_texts(apps, schema_editor):
    ExtractedText = apps.get_model("essays", "ExtractedText")
    Essay = apps.get_model("essays", "Essay")
    for essay in Essay.objects.all():
        extracted_texts = ExtractedText.objects.filter(essay=essay)
        for extracted_text in extracted_texts:
            if extracted_text.extraction_method == TEXTRACT_EXTRACTION_METHOD:
                setattr(essay, "extracted_text1", extracted_text.text)
            elif extracted_text.extraction_method == PEN_TO_PRINT_EXTRACTION_METHOD:
                setattr(essay, "extracted_text2", extracted_text.text)
        essay.save()
    ExtractedText.objects.all().delete()


def create_existing_feedback(apps, schema_editor):
    Essay = apps.get_model("essays", "Essay")
    Feedback = apps.get_model("essays", "Feedback")
    FeedbackCategory = apps.get_model("essays", "FeedbackCategory")
    for essay in Essay.objects.all():
        for i in range(1, 6):
            feedback = getattr(essay, f"feedback{i}")
            grade = getattr(essay, f"grade{i}")
            feedback_category = FeedbackCategory.objects.filter(
                name=f"Competência {i}", essay_type=essay.essay_type
            ).first()
            if feedback:
                Feedback.objects.create(
                    essay=essay,
                    text=feedback,
                    grade=grade,
                    feedback_category=feedback_category,
                )


def reverse_create_existing_feedback(apps, schema_editor):
    Feedback = apps.get_model("essays", "Feedback")
    Essay = apps.get_model("essays", "Essay")
    for essay in Essay.objects.all():
        # Populate feedback and grade fields from Feedback model
        feedbacks = Feedback.objects.filter(essay=essay).order_by(
            "feedback_category__name"
        )
        for feedback in feedbacks:
            competence_number = int(feedback.feedback_category.name.split()[-1])
            setattr(essay, f"feedback{competence_number}", feedback.text)
            setattr(essay, f"grade{competence_number}", feedback.grade)

        essay.save()

    # Delete all Feedback objects
    Feedback.objects.all().delete()


def log_which_fail_constraint(apps, schema_editor):
    Essay = apps.get_model("essays", "Essay")
    # log essays that have the same author and essay_topic combination

    duplicates = (
        Essay.objects.values("author", "essay_topic")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    if duplicates:
        print("Essays that violate the unique constraint (author, essay_topic):")
        for duplicate in duplicates:
            essays = Essay.objects.filter(
                author=duplicate["author"], essay_topic=duplicate["essay_topic"]
            )
            print(
                f"Author: {duplicate['author']}, Essay Topic: {duplicate['essay_topic']}"
            )
            for essay in essays:
                print(f"  Essay ID: {essay.id}, Created At: {essay.created_at}")

        print("\nSQL query to find violating essays:")
        print(connection.queries[-1]["sql"])
    else:
        print("No essays violate the unique constraint (author, essay_topic).")


class Migration(migrations.Migration):

    dependencies = [
        ("essays", "0004_auto_20240611_0918"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "SET CONSTRAINTS ALL IMMEDIATE", reverse_sql="SET CONSTRAINTS ALL DEFERRED"
        ),
        migrations.CreateModel(
            name="EssayType",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RunPython(
            code=create_enem_essay_type,
            reverse_code=reverse_create_enem_essay_type,
        ),
        migrations.AddField(
            model_name="essay",
            name="essay_type",
            field=models.ForeignKey(
                default="Enem",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="essays",
                to="essays.essaytype",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FeedbackCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("prompt_template", models.TextField()),
                ("temperature", models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="feedbackcategory",
            name="essay_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_categories",
                to="essays.essaytype",
            ),
        ),
        migrations.RunPython(
            code=create_enem_feedback_categories,
            reverse_code=reverse_create_enem_feedback_categories,
        ),
        migrations.RunPython(
            code=delete_null_author,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="essay",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essays",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ExtractedText",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("extraction_method", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="extractedtext",
            name="essay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_texts",
                to="essays.essay",
            ),
        ),
        migrations.RunPython(
            code=create_existing_extracted_texts,
            reverse_code=reverse_create_existing_extracted_texts,
        ),
        migrations.RemoveField(
            model_name="essay",
            name="extracted_text1",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="extracted_text2",
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="essays.feedbackcategory",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="essay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="essays.essay",
            ),
        ),
        migrations.RunPython(
            code=create_existing_feedback,
            reverse_code=reverse_create_existing_feedback,
        ),
        migrations.RemoveField(
            model_name="essay",
            name="feedback1",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="feedback2",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="feedback3",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="feedback4",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="feedback5",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="grade1",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="grade2",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="grade3",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="grade4",
        ),
        migrations.RemoveField(
            model_name="essay",
            name="grade5",
        ),
        migrations.RunPython(
            code=log_which_fail_constraint,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="essay",
            constraint=models.UniqueConstraint(
                fields=("author", "essay_topic"), name="unique_essay_per_user_per_topic"
            ),
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["feedback_category__name"]},
        ),
        migrations.AlterField(
            model_name="essay",
            name="essay_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="essays",
                to="essays.essaytype",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedbacks",
                to="essays.feedbackcategory",
            ),
        ),
        migrations.RunSQL(
            "SET CONSTRAINTS ALL DEFERRED", reverse_sql="SET CONSTRAINTS ALL IMMEDIATE"
        ),
    ]
