import time

import requests
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from quiz.models import Challenge, SessionQuestion
from quiz.utils import CATEGORIES, SUBCATEGORIES_TO_PARENT_CATEGORIES

from app.config import settings

User = get_user_model()

# Branch.io API keys
BRANCH_KEY = settings.branch_api_key
BRANCH_KEY_TEST = settings.branch_api_key_test


class Command(BaseCommand):
    help = "Generate Branch.io deep links for all challenges created by generate_challenges_by_category"

    def add_arguments(self, parser):
        parser.add_argument(
            "--user",
            type=str,
            help="Username of the user to associate with the deep links",
            required=True,
        )
        parser.add_argument(
            "--test",
            action="store_true",
            help="Use test Branch.io API key instead of live key",
        )

    def handle(self, *args, **options):
        username = options["user"]
        use_test_key = options["test"]

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            self.stderr.write(self.style.ERROR(f"User {username} does not exist"))
            return

        # Get all challenges created by generate_challenges_by_category
        # These challenges have titles ending with "- Desafio Oficial"
        challenges = Challenge.objects.filter(title__endswith="- Desafio Oficial")

        if not challenges:
            self.stderr.write(self.style.ERROR("No official challenges found"))
            return

        self.stdout.write(
            self.style.SUCCESS(f"Found {challenges.count()} official challenges")
        )

        self.stdout.write("Matéria | Categoria | Subcategoria | Questões | Link")
        self.stdout.write("-" * 100)

        for challenge in challenges:
            subcategory = challenge.title.replace(" - Desafio Oficial", "").strip()

            category = SUBCATEGORIES_TO_PARENT_CATEGORIES.get(subcategory, "Unknown")

            subject = self.find_subject_for_category(category)

            # Count questions using SessionQuestion
            question_count = SessionQuestion.objects.filter(
                session_id=challenge.id
            ).count()

            # Generate Branch.io deep link
            branch_key = BRANCH_KEY_TEST if use_test_key else BRANCH_KEY
            branch_link = self.generate_branch_link(
                challenge_code=challenge.code,
                battle_type="Desafio",
                creator_id=user.id,
                creator_username=user.username,
                branch_key=branch_key,
            )

            # Print result in a single line
            self.stdout.write(
                f"{subject} | {category} | {subcategory} | {question_count} | {branch_link}"
            )

    def find_subject_for_category(self, category):
        """Find which subject (matéria) contains the given category"""
        for subject, categories in CATEGORIES.items():
            if category in categories:
                return subject
        return "Unknown"

    def generate_branch_link(
        self, challenge_code, battle_type, creator_id, creator_username, branch_key
    ):
        """Generate a Branch.io deep link for a challenge"""
        try:
            unique_alias = (
                f"{battle_type}_{challenge_code}_t={int(time.time())}_uId={creator_id}"
            )

            url = "https://api2.branch.io/v1/url"
            data = {
                "branch_key": branch_key,
                "alias": unique_alias,
                "data": {
                    "itemType": "battle",
                    "battleCode": challenge_code,
                    "battleType": battle_type,
                    "creatorId": str(creator_id),
                    "creatorUsername": creator_username,
                    "referrerId": str(creator_id),
                    "referrerUsername": creator_username,
                    "timestamp": str(int(time.time())),
                },
                "title": f"Entre no meu {battle_type}!",
                "description": "Junte-se a mim no Pico!",
                "feature": "backend_invite",
                "channel": "backend_autogenerated",
                "campaign": "official_challenges",
                "$desktop_url": "https://www.usepico.com.br/",
            }

            response = requests.post(url, json=data)
            response.raise_for_status()

            return response.json().get("url")
        except Exception as e:
            self.stderr.write(
                self.style.ERROR(f"Error generating Branch link: {str(e)}")
            )
            return "Error: Failed to generate link"
