"""size optionl on file

Revision ID: e03714ef4af3
Revises: 3febdc1b3823
Create Date: 2025-06-19 23:23:46.321495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.base
import pgvector.sqlalchemy
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision: str = 'e03714ef4af3'
down_revision: Union[str, None] = '3febdc1b3823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
    
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
