"""initial

Revision ID: 7f5b323a78cc
Revises:
Create Date: 2025-05-23 09:20:35.538868

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa

import app.base
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f5b323a78cc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def drop_types() -> None:
    op.execute("DROP TYPE IF EXISTS educationlevel")
    op.execute("DROP TYPE IF EXISTS questiontype")
    op.execute("DROP TYPE IF EXISTS quiztype")
    op.execute("DROP TYPE IF EXISTS questionselectionmethod")
    op.execute("DROP TYPE IF EXISTS duelstatus")
    op.execute("DROP TYPE IF EXISTS duelturnphase")
    op.execute("DROP TYPE IF EXISTS tournamentstatus")
    op.execute("DROP TYPE IF EXISTS currencyaction")
    op.execute("DROP TYPE IF EXISTS currencytype")
    op.execute("DROP TYPE IF EXISTS signupsource")
    op.execute("DROP TYPE IF EXISTS devicetype")
    op.execute("DROP TYPE IF EXISTS flowinputtype")
    op.execute("DROP TYPE IF EXISTS questionsourcetype")
    op.execute("DROP TYPE IF EXISTS questionanswertype")
    op.execute("DROP TYPE IF EXISTS flowdifficulty")
    op.execute("DROP TYPE IF EXISTS questiondifficulty")


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        drop_types()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course")),
    )
    op.create_table(
        "currency",
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "currency_type",
            sa.Enum("PRICE", "REWARD", name="currencytype"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "USER_REFERRED_ANOTHER",
                "ANOTHER_USER_REFERRED_ME",
                "DYNAMIC_RANKING_REWARD",
                "SCHOOL_DYNAMIC_RANKING_REWARD",
                "CUSTOM_QUIZ_CREATION",
                "CUSTOM_QUIZ_JOIN",
                "QUIZ_CREATION",
                "QUIZ_JOIN",
                "CUSTOM_DUEL_CREATION",
                "CUSTOM_DUEL_JOIN",
                "DUEL_CREATION",
                "DUEL_JOIN",
                "ESSAY_CREATION",
                "CUSTOM_CHALLENGE_CREATION",
                "CUSTOM_CHALLENGE_JOIN",
                "CUSTOM_CHALLENGE_COMMISSION",
                "CHALLENGE_CREATION",
                "CHALLENGE_JOIN",
                "CHALLENGE_COMMISSION",
                name="currencyaction",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__currency")),
    )
    op.create_index(
        "unique_default_currency_per_action_type",
        "currency",
        ["action", "currency_type", "is_default"],
        unique=True,
    )
    op.create_table(
        "entity_association",
        sa.Column("discriminator", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__entity_association")),
    )
    op.create_table(
        "file",
        sa.Column("file_id", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__file")),
        sa.UniqueConstraint("file_id", name=op.f("uq__file__file_id")),
    )
    op.create_table(
        "institution",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("institution_type", sa.String(length=50), nullable=False),
        sa.Column("inep_code", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__institution")),
    )
    op.create_index(
        "unique_inep_code",
        "institution",
        ["inep_code"],
        unique=True,
        postgresql_where=sa.text("inep_code != ''"),
    )
    op.create_table(
        "course_college",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("college_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["institution.id"],
            name=op.f("fk__course_college__college_id__institution"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk__course_college__course_id__course"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course_college")),
        sa.UniqueConstraint(
            "course_id",
            "college_id",
            name=op.f("uq__course_college__course_id_college_id"),
        ),
    )
    op.create_table(
        "education",
        sa.Column(
            "level",
            sa.Enum(
                "MIDDLE_SCHOOL",
                "FIRST_YEAR_HIGH_SCHOOL",
                "SECOND_YEAR_HIGH_SCHOOL",
                "THIRD_YEAR_HIGH_SCHOOL",
                "HIGH_SCHOOL_COMPLETE",
                "COLLEGE",
                "UNKNOWN",
                name="educationlevel",
            ),
            nullable=False,
        ),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("fk__education__course_id__course")
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk__education__institution_id__institution"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__education")),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=25), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("bot_difficulty", sa.Float(), nullable=True),
        sa.Column(
            "signup_source",
            sa.Enum(
                "REFERRAL",
                "SOCIAL",
                "INTERNET",
                "TEACHER",
                "EVENT",
                "OTHER",
                "UNKNOWN",
                name="signupsource",
            ),
            nullable=False,
        ),
        sa.Column("current_education_id", sa.Integer(), nullable=True),
        sa.Column("intended_education_id", sa.Integer(), nullable=True),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entity_association_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "is_bot = False AND bot_difficulty IS NULL OR is_bot = True AND bot_difficulty IS NOT NULL",
            name=op.f("ck__user__bot_difficulty_check"),
        ),
        sa.ForeignKeyConstraint(
            ["current_education_id"],
            ["education.id"],
            name=op.f("fk__user__current_education_id__education"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_association_id"],
            ["entity_association.id"],
            name=op.f("fk__user__entity_association_id__entity_association"),
        ),
        sa.ForeignKeyConstraint(
            ["intended_education_id"],
            ["education.id"],
            name=op.f("fk__user__intended_education_id__education"),
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_id"], ["user.id"], name=op.f("fk__user__referred_by_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
        sa.UniqueConstraint("email", name=op.f("uq__user__email")),
        sa.UniqueConstraint("phone_number", name=op.f("uq__user__phone_number")),
        sa.UniqueConstraint("username", name=op.f("uq__user__username")),
    )
    op.create_index(
        "ix_user_email_lower", "user", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_index(
        "ix_user_username_lower",
        "user",
        [sa.literal_column("lower(username)")],
        unique=True,
    )
    op.create_table(
        "currency_transaction",
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("entity_association_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
            name=op.f("fk__currency_transaction__currency_id__currency"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_association_id"],
            ["entity_association.id"],
            name=op.f(
                "fk__currency_transaction__entity_association_id__entity_association"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__currency_transaction__user_id__user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__currency_transaction")),
    )
    op.create_table(
        "fcm_device",
        sa.Column("registration_id", sa.String(length=255), nullable=False),
        sa.Column(
            "device_type",
            sa.Enum("ANDROID", "IOS", "WEB", name="devicetype"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__fcm_device__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fcm_device")),
        sa.UniqueConstraint(
            "registration_id", name=op.f("uq__fcm_device__registration_id")
        ),
        sa.UniqueConstraint("user_id", name=op.f("uq__fcm_device__user_id")),
    )
    op.create_table(
        "flow",
        sa.Column(
            "code",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("cover_image_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("area", sa.Text(), nullable=False),
        sa.Column("source_filter", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("ALL", "EASY", "MEDIUM", "HARD", name="flowdifficulty"),
            nullable=False,
        ),
        sa.Column(
            "question_answer_type",
            sa.Enum("MULTIPLE_CHOICE", "OPEN_ENDED", name="questionanswertype"),
            nullable=False,
        ),
        sa.Column(
            "flow_input_type",
            sa.Enum("TOPIC", "FILES", "USER_DATA", name="flowinputtype"),
            nullable=False,
        ),
        sa.Column("input_topic", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_image_id"], ["file.id"], name=op.f("fk__flow__cover_image_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["user.id"], name=op.f("fk__flow__created_by_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow")),
    )
    op.create_table(
        "question",
        sa.Column("content_blocks", app.base.ContentBlockListType(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=False),
        sa.Column("caderno", sa.String(length=255), nullable=False),
        sa.Column("caderno_number", sa.Integer(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="questiondifficulty"),
            nullable=False,
        ),
        sa.Column("parameter_a", sa.Float(), nullable=True),
        sa.Column("parameter_b", sa.Float(), nullable=True),
        sa.Column("parameter_c", sa.Float(), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("answer_image_id", sa.Integer(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.Column(
            "source_type",
            sa.Enum("OFFICIAL", "AI_GENERATED", name="questionsourcetype"),
            nullable=False,
        ),
        sa.Column("official_source", sa.String(), nullable=False),
        sa.Column("source_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "answer_type",
            sa.Enum("MULTIPLE_CHOICE", "OPEN_ENDED", name="questionanswertype"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_image_id"],
            ["file.id"],
            name=op.f("fk__question__answer_image_id__file"),
        ),
        sa.ForeignKeyConstraint(
            ["source_user_id"],
            ["user.id"],
            name=op.f("fk__question__source_user_id__user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__question")),
    )
    op.create_index(
        "question_embedding_index",
        "question",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "user_profile",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("social_score", sa.Integer(), nullable=False),
        sa.Column("xp_score", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__user_profile__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_profile")),
        sa.UniqueConstraint("user_id", name=op.f("uq__user_profile__user_id")),
    )
    op.create_table(
        "user_websocket_info",
        sa.Column(
            "last_websocket_connection", sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column(
            "last_websocket_disconnection", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__user_websocket_info__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_websocket_info")),
        sa.UniqueConstraint("user_id", name=op.f("uq__user_websocket_info__user_id")),
    )
    op.create_table(
        "choice",
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["file.id"], name=op.f("fk__choice__image_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk__choice__question_id__question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__choice")),
        sa.UniqueConstraint(
            "question_id", "order", name=op.f("uq__choice__question_id_order")
        ),
    )
    op.create_table(
        "flow_element",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("element_type", sa.Text(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(element_type = 'question' AND question_id IS NOT NULL)",
            name=op.f("ck__flow_element__ck_flowelement_exactly_one_payload"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__flow_element__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk__flow_element__question_id__question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_element")),
        sa.UniqueConstraint(
            "flow_id", "order", name=op.f("uq__flow_element__flow_id_order")
        ),
        sa.UniqueConstraint(
            "flow_id", "question_id", name=op.f("uq__flow_element__flow_id_question_id")
        ),
    )
    op.create_table(
        "flow_transcription_block",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("block_text", sa.Text(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__flow_transcription_block__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_transcription_block")),
        sa.UniqueConstraint(
            "flow_id",
            "block_number",
            name=op.f("uq__flow_transcription_block__flow_id_block_number"),
        ),
    )
    op.create_table(
        "flow_question_user",
        sa.Column("flow_element_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("choice_id", sa.Integer(), nullable=True),
        sa.Column("submitted_text", sa.Text(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("grade", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (choice_id IS NOT NULL AND submitted_text = '') OR\n            (choice_id IS NULL AND submitted_text != '')\n            ",
            name=op.f(
                "ck__flow_question_user__check_flow_question_user_answer_valid_states"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["choice.id"],
            name=op.f("fk__flow_question_user__choice_id__choice"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_element_id"],
            ["flow_element.id"],
            name=op.f("fk__flow_question_user__flow_element_id__flow_element"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__flow_question_user__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_question_user")),
        sa.UniqueConstraint(
            "flow_element_id",
            "user_id",
            name=op.f("uq__flow_question_user__flow_element_id_user_id"),
        ),
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, email, phone_number, hashed_password, is_superuser, 
                               is_premium, balance, is_bot, 
                               bot_difficulty, signup_source)
            VALUES ('system', 'system@example.com', '21999202122', '', 
                    false, false, 0, false,
                    NULL, 'OTHER'),
                    ('pico', 'pico@example.com', '21999202123', '', 
                    false, false, 0, false,
                    NULL, 'OTHER'),
                    ('deleted', 'deleted@example.com', '21999202124', '', 
                    false, false, 0, false,
                    NULL, 'OTHER');
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flow_question_user")
    op.drop_table("flow_transcription_block")
    op.drop_table("flow_element")
    op.drop_table("choice")
    op.drop_table("user_websocket_info")
    op.drop_table("user_profile")
    op.drop_index(
        "question_embedding_index",
        table_name="question",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("question")
    op.drop_table("flow")
    op.drop_table("fcm_device")
    op.drop_table("currency_transaction")
    op.drop_index("ix_user_username_lower", table_name="user")
    op.drop_index("ix_user_email_lower", table_name="user")
    op.drop_table("user")
    op.drop_table("education")
    op.drop_table("course_college")
    op.drop_index(
        "unique_inep_code",
        table_name="institution",
        postgresql_where=sa.text("inep_code != ''"),
    )
    op.drop_table("institution")
    op.drop_table("file")
    op.drop_table("entity_association")
    op.drop_index("unique_default_currency_per_action_type", table_name="currency")
    op.drop_table("currency")
    op.drop_table("course")
    # ### end Alembic commands ###

    # Only drop types if it's the first migration
    if not down_revision:
        drop_types()
