"""stuff

Revision ID: 26a31b8bb795
Revises: 7f5b323a78cc
Create Date: 2025-05-26 19:51:08.470771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.base
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '26a31b8bb795'
down_revision: Union[str, None] = '7f5b323a78cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def drop_types() -> None:
    op.execute("DROP TYPE IF EXISTS educationlevel")
    op.execute("DROP TYPE IF EXISTS questiontype")
    op.execute("DROP TYPE IF EXISTS quiztype")
    op.execute("DROP TYPE IF EXISTS questionselectionmethod")
    op.execute("DROP TYPE IF EXISTS duelstatus")
    op.execute("DROP TYPE IF EXISTS duelturnphase")
    op.execute("DROP TYPE IF EXISTS tournamentstatus")
    op.execute("DROP TYPE IF EXISTS currencyaction")
    op.execute("DROP TYPE IF EXISTS currencytype")
    op.execute("DROP TYPE IF EXISTS signupsource")
    op.execute("DROP TYPE IF EXISTS devicetype")
    op.execute("DROP TYPE IF EXISTS flowinputtype")
    op.execute("DROP TYPE IF EXISTS questionsourcetype")
    op.execute("DROP TYPE IF EXISTS questionanswertype")
    op.execute("DROP TYPE IF EXISTS flowdifficulty")
    op.execute("DROP TYPE IF EXISTS questiondifficulty")

def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        drop_types()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__exam'))
    )
    op.create_table('campaign',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('action_link', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('num_questions_for_trigger_first', sa.Integer(), nullable=False),
    sa.Column('num_questions_for_trigger_recurring', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['file.id'], name=op.f('fk__campaign__cover_image_id__file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__campaign'))
    )
    op.create_table('official_question_source',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk__official_question_source__exam_id__exam'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__official_question_source'))
    )
    op.create_table('flow_user_feed',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name=op.f('fk__flow_user_feed__flow_id__flow'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__flow_user_feed__user_id__user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__flow_user_feed')),
    sa.UniqueConstraint('user_id', 'flow_id', name=op.f('uq__flow_user_feed__user_id_flow_id'))
    )
    op.add_column('flow', sa.Column('action_link', sa.Text(), nullable=False))
    op.add_column('flow', sa.Column('action_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###
    
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, email, phone_number, hashed_password, is_superuser, 
                               is_premium, balance, is_bot, 
                               bot_difficulty, signup_source)
            VALUES ('system', 'system@example.com', '21999202122', '', 
                    false, false, 0, false,
                    NULL, 'OTHER'),
                    ('pico', 'pico@example.com', '21999202123', '', 
                    false, false, 0, false,
                    NULL, 'OTHER'),
                    ('deleted', 'deleted@example.com', '21999202124', '', 
                    false, false, 0, false,
                    NULL, 'OTHER');
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'action_text')
    op.drop_column('flow', 'action_link')
    op.drop_table('flow_user_feed')
    op.drop_table('official_question_source')
    op.drop_table('campaign')
    op.drop_table('exam')
    # ### end Alembic commands ###
    
    # Only drop types if it's the first migration
    if not down_revision:
        drop_types()
