"""initial

Revision ID: 283b2bc70b03
Revises:
Create Date: 2025-06-11 16:51:56.538853

"""

from typing import Sequence, Union

import geoalchemy2.types
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.base
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "283b2bc70b03"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subtitle", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__community")),
        sa.UniqueConstraint(
            "name", "subtitle", name=op.f("uq__community__name_subtitle")
        ),
    )
    op.create_table(
        "country",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone_code", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__country")),
        sa.UniqueConstraint("code", name=op.f("uq__country__code")),
    )
    op.create_table(
        "education_level",
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__education_level")),
    )
    op.create_table(
        "file",
        sa.Column("file_id", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__file")),
        sa.UniqueConstraint("file_id", name=op.f("uq__file__file_id")),
    )
    op.create_table(
        "campaign",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("external_link", sa.Text(), nullable=False),
        sa.Column("external_link_text", sa.Text(), nullable=False),
        sa.Column("image1_id", sa.Integer(), nullable=True),
        sa.Column("image2_id", sa.Integer(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column(
            "campaign_type",
            sa.Enum(
                "EXTERNAL",
                "INSTITUTION",
                "INTENDED_EDUCATION",
                "REFERRALS",
                "FLOW",
                "ADD_PHONE_NUMBER",
                name="campaigntype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image1_id"], ["file.id"], name=op.f("fk__campaign__image1_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["image2_id"], ["file.id"], name=op.f("fk__campaign__image2_id__file")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__campaign")),
    )
    op.create_table(
        "course",
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["education_level.id"],
            name=op.f("fk__course__level_id__education_level"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course")),
    )
    op.create_table(
        "institution",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("institution_type", sa.String(length=50), nullable=False),
        sa.Column("government_issued_code", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("administrative_category", sa.String(length=50), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk__institution__country_code__country"),
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["education_level.id"],
            name=op.f("fk__institution__level_id__education_level"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__institution")),
    )
    op.create_index(
        "unique_government_code_per_country",
        "institution",
        ["government_issued_code", "country_code"],
        unique=True,
        postgresql_where=sa.text("government_issued_code != ''"),
    )
    op.create_table(
        "level_stage",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk__level_stage__country_code__country"),
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["education_level.id"],
            name=op.f("fk__level_stage__level_id__education_level"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__level_stage")),
        sa.UniqueConstraint(
            "name", "level_id", "country_code", name="unique_level_stage_per_country"
        ),
    )
    op.create_table(
        "education_info",
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("stage_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk__education_info__course_id__course"),
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk__education_info__institution_id__institution"),
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["education_level.id"],
            name=op.f("fk__education_info__level_id__education_level"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["level_stage.id"],
            name=op.f("fk__education_info__stage_id__level_stage"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__education_info")),
    )
    op.create_table(
        "exam",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("education_level_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk__exam__country_code__country"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("fk__exam__course_id__course")
        ),
        sa.ForeignKeyConstraint(
            ["education_level_id"],
            ["education_level.id"],
            name=op.f("fk__exam__education_level_id__education_level"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__exam")),
    )
    op.create_table(
        "question_area",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("education_level_id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk__question_area__country_code__country"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk__question_area__course_id__course"),
        ),
        sa.ForeignKeyConstraint(
            ["education_level_id"],
            ["education_level.id"],
            name=op.f("fk__question_area__education_level_id__education_level"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__question_area")),
    )
    op.create_table(
        "official_question_source",
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exam.id"],
            name=op.f("fk__official_question_source__exam_id__exam"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__official_question_source")),
    )
    op.create_table(
        "user",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=25), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "google_id", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column("apple_id", sa.String(length=255), server_default="", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("bot_difficulty", sa.Float(), nullable=True),
        sa.Column(
            "signup_source",
            sa.Enum(
                "REFERRAL",
                "SOCIAL",
                "INTERNET",
                "TEACHER",
                "EVENT",
                "OTHER",
                "UNKNOWN",
                name="signupsource",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("current_education_id", sa.Integer(), nullable=True),
        sa.Column("intended_education_id", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("social_score", sa.Integer(), nullable=False),
        sa.Column("xp_score", sa.Integer(), nullable=False),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(google_id != '' AND apple_id = '' AND hashed_password = '') OR (google_id = '' AND apple_id != '' AND hashed_password = '') OR (google_id = '' AND apple_id = '' AND hashed_password != '') OR (google_id = '' AND apple_id = '' AND hashed_password = '')",
            name=op.f("ck__user__google_or_apple_or_password_exclusive_check"),
        ),
        sa.CheckConstraint(
            "is_bot = False AND bot_difficulty IS NULL OR is_bot = True AND bot_difficulty IS NOT NULL",
            name=op.f("ck__user__bot_difficulty_check"),
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk__user__country_code__country"),
        ),
        sa.ForeignKeyConstraint(
            ["current_education_id"],
            ["education_info.id"],
            name=op.f("fk__user__current_education_id__education_info"),
        ),
        sa.ForeignKeyConstraint(
            ["intended_education_id"],
            ["education_info.id"],
            name=op.f("fk__user__intended_education_id__education_info"),
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_id"], ["user.id"], name=op.f("fk__user__referred_by_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
        sa.UniqueConstraint("email", name=op.f("uq__user__email")),
        sa.UniqueConstraint("username", name=op.f("uq__user__username")),
    )
    op.create_index(
        "ix_user_email_lower", "user", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_index(
        "unique_apple_id",
        "user",
        ["apple_id"],
        unique=True,
        postgresql_where=sa.text("apple_id != ''"),
    )
    op.create_index(
        "unique_current_education_id",
        "user",
        ["current_education_id"],
        unique=True,
        postgresql_where=sa.text("current_education_id IS NULL"),
    )
    op.create_index(
        "unique_google_id",
        "user",
        ["google_id"],
        unique=True,
        postgresql_where=sa.text("google_id != ''"),
    )
    op.create_index(
        "unique_intended_education_id",
        "user",
        ["intended_education_id"],
        unique=True,
        postgresql_where=sa.text("intended_education_id IS NULL"),
    )
    op.create_table(
        "community_user",
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
            name=op.f("fk__community_user__community_id__community"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__community_user__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__community_user")),
        sa.UniqueConstraint(
            "community_id",
            "user_id",
            name=op.f("uq__community_user__community_id_user_id"),
        ),
    )
    op.create_table(
        "fcm_device",
        sa.Column("registration_id", sa.String(length=255), nullable=False),
        sa.Column(
            "device_type",
            sa.Enum(
                "ANDROID", "IOS", "WEB", name="devicetype", native_enum=False, length=50
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__fcm_device__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__fcm_device")),
        sa.UniqueConstraint(
            "registration_id", name=op.f("uq__fcm_device__registration_id")
        ),
        sa.UniqueConstraint("user_id", name=op.f("uq__fcm_device__user_id")),
    )
    op.create_table(
        "flow",
        sa.Column(
            "code",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("cover_image_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("action_link", sa.Text(), nullable=False),
        sa.Column("action_text", sa.Text(), nullable=False),
        sa.Column("max_num_questions", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "ALL",
                "EASY",
                "MEDIUM",
                "HARD",
                name="flowdifficulty",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "question_answer_type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "OPEN_ENDED",
                name="questionanswertype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "OFFICIAL",
                "AI_GENERATED",
                "FULL",
                name="flowsourcetype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "flow_input_type",
            sa.Enum(
                "TOPIC",
                "FILES",
                "USER_DATA",
                name="flowinputtype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("input_topic", sa.Text(), nullable=False),
        sa.Column("major_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("minor_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_image_id"], ["file.id"], name=op.f("fk__flow__cover_image_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["user.id"], name=op.f("fk__flow__created_by_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow")),
    )
    op.create_table(
        "question",
        sa.Column(
            "content_blocks", app.flows.db_types.ContentBlockListType(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_quantitative", sa.Boolean(), nullable=False),
        sa.Column("major_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("minor_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "EASY",
                "MEDIUM",
                "HARD",
                name="questiondifficulty",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("parameter_a", sa.Float(), nullable=True),
        sa.Column("parameter_b", sa.Float(), nullable=True),
        sa.Column("parameter_c", sa.Float(), nullable=True),
        sa.Column(
            "answer_content_blocks",
            app.flows.db_types.ContentBlockListType(),
            nullable=False,
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "OFFICIAL",
                "AI_GENERATED",
                name="questionsourcetype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("official_source_id", sa.Integer(), nullable=True),
        sa.Column("source_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "answer_type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "OPEN_ENDED",
                name="questionanswertype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["official_source_id"],
            ["official_question_source.id"],
            name=op.f("fk__question__official_source_id__official_question_source"),
        ),
        sa.ForeignKeyConstraint(
            ["source_user_id"],
            ["user.id"],
            name=op.f("fk__question__source_user_id__user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__question")),
    )
    op.create_index(
        "question_embedding_index",
        "question",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "user_websocket_info",
        sa.Column(
            "last_websocket_connection", sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column(
            "last_websocket_disconnection", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__user_websocket_info__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_websocket_info")),
        sa.UniqueConstraint("user_id", name=op.f("uq__user_websocket_info__user_id")),
    )
    op.create_table(
        "choice",
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["file.id"], name=op.f("fk__choice__image_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk__choice__question_id__question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__choice")),
        sa.UniqueConstraint(
            "question_id", "order", name=op.f("uq__choice__question_id_order")
        ),
    )
    op.create_table(
        "flow_element",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("element_type", sa.Text(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(element_type = 'flow_question' AND question_id IS NOT NULL)",
            name=op.f("ck__flow_element__ck_flowelement_exactly_one_payload"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__flow_element__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk__flow_element__question_id__question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_element")),
        sa.UniqueConstraint(
            "flow_id", "order", name=op.f("uq__flow_element__flow_id_order")
        ),
        sa.UniqueConstraint(
            "flow_id", "question_id", name=op.f("uq__flow_element__flow_id_question_id")
        ),
    )
    op.create_table(
        "flow_transcription_block",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("block_text", sa.Text(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__flow_transcription_block__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_transcription_block")),
        sa.UniqueConstraint(
            "flow_id",
            "block_number",
            name=op.f("uq__flow_transcription_block__flow_id_block_number"),
        ),
    )
    op.create_table(
        "flow_user_feed",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__flow_user_feed__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__flow_user_feed__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_user_feed")),
        sa.UniqueConstraint(
            "user_id", "flow_id", name=op.f("uq__flow_user_feed__user_id_flow_id")
        ),
    )
    op.create_table(
        "in_app_notification",
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("in_app_notification_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_url", sa.Text(), nullable=False),
        sa.Column("flow_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__in_app_notification__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__in_app_notification__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__in_app_notification")),
    )
    op.create_table(
        "flow_question_user",
        sa.Column("flow_element_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("choice_id", sa.Integer(), nullable=True),
        sa.Column("submitted_text", sa.Text(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("grade", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (choice_id IS NOT NULL AND submitted_text = '') OR\n            (choice_id IS NULL AND submitted_text != '') OR\n            (choice_id IS NULL AND submitted_text = '')\n            ",
            name=op.f(
                "ck__flow_question_user__check_flow_question_user_answer_valid_states"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["choice.id"],
            name=op.f("fk__flow_question_user__choice_id__choice"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_element_id"],
            ["flow_element.id"],
            name=op.f("fk__flow_question_user__flow_element_id__flow_element"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__flow_question_user__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_question_user")),
        sa.UniqueConstraint(
            "flow_element_id",
            "user_id",
            name=op.f("uq__flow_question_user__flow_element_id_user_id"),
        ),
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flow_question_user")
    op.drop_table("in_app_notification")
    op.drop_table("flow_user_feed")
    op.drop_table("flow_transcription_block")
    op.drop_table("flow_element")
    op.drop_table("choice")
    op.drop_table("user_websocket_info")
    op.drop_index(
        "question_embedding_index",
        table_name="question",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("question")
    op.drop_table("flow")
    op.drop_table("fcm_device")
    op.drop_table("community_user")
    op.drop_index(
        "unique_intended_education_id",
        table_name="user",
        postgresql_where=sa.text("intended_education_id IS NULL"),
    )
    op.drop_index(
        "unique_google_id",
        table_name="user",
        postgresql_where=sa.text("google_id != ''"),
    )
    op.drop_index(
        "unique_current_education_id",
        table_name="user",
        postgresql_where=sa.text("current_education_id IS NULL"),
    )
    op.drop_index(
        "unique_apple_id", table_name="user", postgresql_where=sa.text("apple_id != ''")
    )
    op.drop_index("ix_user_email_lower", table_name="user")
    op.drop_table("user")
    op.drop_table("official_question_source")
    op.drop_table("question_area")
    op.drop_table("exam")
    op.drop_table("education_info")
    op.drop_table("level_stage")
    op.drop_index(
        "unique_government_code_per_country",
        table_name="institution",
        postgresql_where=sa.text("government_issued_code != ''"),
    )
    op.drop_table("institution")
    op.drop_table("course")
    op.drop_table("campaign")
    op.drop_table("file")
    op.drop_table("education_level")
    op.drop_table("country")
    op.drop_table("community")
    # ### end Alembic commands ###
