"""cascade flow user delete

Revision ID: 3d65ae6bdf2b
Revises: 0848784862f8
Create Date: 2025-08-22 23:28:33.891514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d65ae6bdf2b"
down_revision: Union[str, None] = "0848784862f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__flow__created_by_id__user"), "flow", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__flow__created_by_id__user"),
        "flow",
        "user",
        ["created_by_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__flow__created_by_id__user"), "flow", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__flow__created_by_id__user"), "flow", "user", ["created_by_id"], ["id"]
    )
    # ### end Alembic commands ###
