"""pgroonga

Revision ID: 25e6ace28f32
Revises: 835e3554f78b
Create Date: 2025-06-13 08:10:49.165277

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25e6ace28f32"
down_revision: Union[str, None] = "835e3554f78b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pgroonga"))

    print("i ran!!!!!")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_flow_major_tags_pgroonga",
        "flow",
        ["major_tags"],
        unique=False,
        postgresql_using="pgroonga",
    )
    op.create_index(
        "idx_flow_minor_tags_pgroonga",
        "flow",
        ["minor_tags"],
        unique=False,
        postgresql_using="pgroonga",
    )
    op.create_index(
        "idx_question_major_tags_pgroonga",
        "question",
        ["major_tags"],
        unique=False,
        postgresql_using="pgroonga",
    )
    op.create_index(
        "idx_question_minor_tags_pgroonga",
        "question",
        ["minor_tags"],
        unique=False,
        postgresql_using="pgroonga",
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        with open("app/countries/countries.sql", "r") as f:
            op.execute(f.read())
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, country_code, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 'BR', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_question_minor_tags_pgroonga",
        table_name="question",
        postgresql_using="pgroonga",
    )
    op.drop_index(
        "idx_question_major_tags_pgroonga",
        table_name="question",
        postgresql_using="pgroonga",
    )
    op.drop_index(
        "idx_flow_minor_tags_pgroonga", table_name="flow", postgresql_using="pgroonga"
    )
    op.drop_index(
        "idx_flow_major_tags_pgroonga", table_name="flow", postgresql_using="pgroonga"
    )
    # ### end Alembic commands ###
