"""is privileged

Revision ID: 43e2d2faeca3
Revises: b4fe22735709
Create Date: 2025-07-24 20:56:46.569301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.base
import pgvector.sqlalchemy
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision: str = '43e2d2faeca3'
down_revision: Union[str, None] = 'b4fe22735709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('is_privileged', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###
    
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'is_privileged')
    # ### end Alembic commands ###
