"""cascade question of user

Revision ID: 1816ace8ae2f
Revises: 3d65ae6bdf2b
Create Date: 2025-08-23 22:32:39.645114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1816ace8ae2f"
down_revision: Union[str, None] = "3d65ae6bdf2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__question__source_user_id__user"), "question", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__question__source_user_id__user"),
        "question",
        "user",
        ["source_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__question__source_user_id__user"), "question", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__question__source_user_id__user"),
        "question",
        "user",
        ["source_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
