"""initial

Revision ID: b542b656c9dd
Revises:
Create Date: 2025-04-01 09:24:48.462678

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b542b656c9dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "college",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__college")),
        sa.UniqueConstraint("name", name=op.f("uq__college__name")),
    )
    op.create_table(
        "course",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course")),
        sa.UniqueConstraint("name", name=op.f("uq__course__name")),
    )
    op.create_table(
        "currency",
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "currency_type",
            sa.Enum("PRICE", "REWARD", name="currencytype"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "USER_REFERRED_ANOTHER",
                "ANOTHER_USER_REFERRED_ME",
                "DYNAMIC_RANKING_REWARD",
                "SCHOOL_DYNAMIC_RANKING_REWARD",
                "CUSTOM_QUIZ_CREATION",
                "CUSTOM_QUIZ_JOIN",
                "QUIZ_CREATION",
                "QUIZ_JOIN",
                "CUSTOM_DUEL_CREATION",
                "CUSTOM_DUEL_JOIN",
                "DUEL_CREATION",
                "DUEL_JOIN",
                "ESSAY_CREATION",
                "CUSTOM_CHALLENGE_CREATION",
                "CUSTOM_CHALLENGE_JOIN",
                "CUSTOM_CHALLENGE_COMMISSION",
                "CHALLENGE_CREATION",
                "CHALLENGE_JOIN",
                "CHALLENGE_COMMISSION",
                name="currencyaction",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__currency")),
    )
    op.create_index(
        "unique_default_currency_per_action_type",
        "currency",
        ["action", "currency_type", "is_default"],
        unique=True,
    )
    op.create_table(
        "entity_association",
        sa.Column("discriminator", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__entity_association")),
    )
    op.create_table(
        "essay_topic",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__essay_topic")),
        sa.UniqueConstraint("name", name=op.f("uq__essay_topic__name")),
    )
    op.create_table(
        "essay_type",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__essay_type")),
        sa.UniqueConstraint("name", name=op.f("uq__essay_type__name")),
    )
    op.create_table(
        "file",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__file")),
    )
    op.create_table(
        "school",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("user_submitted", sa.Boolean(), nullable=False),
        sa.Column("inep_code", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__school")),
    )
    op.create_index(
        "unique_inep_code",
        "school",
        ["inep_code"],
        unique=True,
        postgresql_where=sa.text("inep_code != ''"),
    )
    op.create_table(
        "tournament",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UPCOMING", "ONGOING", "COMPLETED", name="tournamentstatus"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__tournament")),
        sa.UniqueConstraint("code", name=op.f("uq__tournament__code")),
    )
    op.create_table(
        "course_college",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("college_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["college.id"],
            name=op.f("fk__course_college__college_id__college"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk__course_college__course_id__course"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course_college")),
        sa.UniqueConstraint(
            "course_id",
            "college_id",
            name=op.f("uq__course_college__course_id_college_id"),
        ),
    )
    op.create_table(
        "feedback_category",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Double(precision=53), nullable=False),
        sa.Column("essay_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["essay_type_id"],
            ["essay_type.id"],
            name=op.f("fk__feedback_category__essay_type_id__essay_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__feedback_category")),
    )
    op.create_table(
        "question",
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("allow_resubmit", sa.Boolean(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("extra_embedding_text", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(length=255), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("answer_image_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("caderno", sa.String(length=255), nullable=False),
        sa.Column("caderno_number", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.String(length=10), nullable=False),
        sa.Column("parameter_a", sa.Float(), nullable=True),
        sa.Column("parameter_b", sa.Float(), nullable=True),
        sa.Column("parameter_c", sa.Float(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=False),
        sa.Column("is_fast", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_image_id"],
            ["file.id"],
            name=op.f("fk__question__answer_image_id__file"),
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["file.id"], name=op.f("fk__question__image_id__file")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__question")),
    )
    op.create_table(
        "tournament_prize",
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
            name=op.f("fk__tournament_prize__tournament_id__tournament"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__tournament_prize")),
        sa.UniqueConstraint(
            "tournament_id",
            "rank",
            name=op.f("uq__tournament_prize__tournament_id_rank"),
        ),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=25), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "education_level",
            sa.Enum(
                "MIDDLE_SCHOOL",
                "FIRST_YEAR_HIGH_SCHOOL",
                "SECOND_YEAR_HIGH_SCHOOL",
                "THIRD_YEAR_HIGH_SCHOOL",
                "HIGH_SCHOOL_COMPLETE",
                "COLLEGE",
                "UNKNOWN",
                name="educationlevel",
            ),
            nullable=False,
        ),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("commitment", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("bot_difficulty", sa.Float(), nullable=True),
        sa.Column(
            "signup_source",
            sa.Enum(
                "REFERRAL",
                "SOCIAL",
                "INTERNET",
                "TEACHER",
                "EVENT",
                "OTHER",
                "UNKNOWN",
                name="signupsource",
            ),
            nullable=False,
        ),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("chosen_college_id", sa.Integer(), nullable=True),
        sa.Column("chosen_course_id", sa.Integer(), nullable=True),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entity_association_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "is_bot = False AND bot_difficulty IS NULL OR is_bot = True AND bot_difficulty IS NOT NULL",
            name=op.f("ck__user__bot_difficulty_check"),
        ),
        sa.ForeignKeyConstraint(
            ["chosen_college_id"],
            ["college.id"],
            name=op.f("fk__user__chosen_college_id__college"),
        ),
        sa.ForeignKeyConstraint(
            ["chosen_course_id"],
            ["course.id"],
            name=op.f("fk__user__chosen_course_id__course"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_association_id"],
            ["entity_association.id"],
            name=op.f("fk__user__entity_association_id__entity_association"),
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_id"], ["user.id"], name=op.f("fk__user__referred_by_id__user")
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name=op.f("fk__user__school_id__school")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
        sa.UniqueConstraint("email", name=op.f("uq__user__email")),
        sa.UniqueConstraint("phone_number", name=op.f("uq__user__phone_number")),
        sa.UniqueConstraint("username", name=op.f("uq__user__username")),
    )
    op.create_index(
        "ix_user_email_lower", "user", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_index(
        "ix_user_username_lower",
        "user",
        [sa.literal_column("lower(username)")],
        unique=True,
    )
    op.create_table(
        "choice",
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["file.id"], name=op.f("fk__choice__image_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk__choice__question_id__question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__choice")),
        sa.UniqueConstraint(
            "question_id", "order", name=op.f("uq__choice__question_id_order")
        ),
    )
    op.create_table(
        "currency_transaction",
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("entity_association_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
            name=op.f("fk__currency_transaction__currency_id__currency"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_association_id"],
            ["entity_association.id"],
            name=op.f(
                "fk__currency_transaction__entity_association_id__entity_association"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__currency_transaction__user_id__user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__currency_transaction")),
    )
    op.create_table(
        "essay",
        sa.Column("original_file", sa.String(length=100), nullable=False),
        sa.Column("cleaned_text", sa.Text(), nullable=False),
        sa.Column("user_corrected_text", sa.Text(), nullable=False),
        sa.Column("essay_topic_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("essay_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entity_association_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
            name=op.f("fk__essay__author_id__user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_association_id"],
            ["entity_association.id"],
            name=op.f("fk__essay__entity_association_id__entity_association"),
        ),
        sa.ForeignKeyConstraint(
            ["essay_topic_id"],
            ["essay_topic.id"],
            name=op.f("fk__essay__essay_topic_id__essay_topic"),
        ),
        sa.ForeignKeyConstraint(
            ["essay_type_id"],
            ["essay_type.id"],
            name=op.f("fk__essay__essay_type_id__essay_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__essay")),
        sa.UniqueConstraint(
            "author_id",
            "essay_topic_id",
            name=op.f("uq__essay__author_id_essay_topic_id"),
        ),
    )
    op.create_table(
        "session",
        sa.Column("session_type", sa.String(length=20), nullable=False),
        sa.Column("query", sa.String(length=255), nullable=False),
        sa.Column("area", sa.String(length=255), nullable=False),
        sa.Column("source_filter", sa.String(length=255), nullable=False),
        sa.Column("difficulty", sa.String(length=50), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("parent_session_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("entity_association_id", sa.Integer(), nullable=True),
        sa.Column(
            "question_type",
            sa.Enum("MULTIPLE_CHOICE", "OPEN_ENDED", "ALL", name="questiontype"),
            nullable=True,
        ),
        sa.Column(
            "quiz_type",
            sa.Enum("QUERY_BASED", "PERSONALIZED", "CUSTOM", name="quiztype"),
            nullable=True,
        ),
        sa.Column("is_fast", sa.Boolean(), nullable=True),
        sa.Column(
            "selection_method",
            sa.Enum(
                "RANDOM_OFFICIAL",
                "QUERY_OFFICIAL",
                "USER_GENERATED",
                name="questionselectionmethod",
            ),
            nullable=True,
        ),
        sa.Column("n_questions_per_round", sa.Integer(), nullable=True),
        sa.Column(
            "duel_status",
            sa.Enum("IN_PROGRESS", "COMPLETED", "ABANDONED", name="duelstatus"),
            nullable=True,
        ),
        sa.Column("current_turn_id", sa.Integer(), nullable=True),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name=op.f("fk__session__created_by_id__user"),
        ),
        sa.ForeignKeyConstraint(
            ["current_turn_id"],
            ["turn.id"],
            name=op.f("fk__session__current_turn_id__turn"),
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["entity_association_id"],
            ["entity_association.id"],
            name=op.f("fk__session__entity_association_id__entity_association"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file.id"], name=op.f("fk__session__file_id__file")
        ),
        sa.ForeignKeyConstraint(
            ["parent_session_id"],
            ["session.id"],
            name=op.f("fk__session__parent_session_id__session"),
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
            name=op.f("fk__session__tournament_id__tournament"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"], ["user.id"], name=op.f("fk__session__winner_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__session")),
        sa.UniqueConstraint("code", name=op.f("uq__session__code")),
    )
    op.create_table(
        "tournament_participation",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
            name=op.f("fk__tournament_participation__tournament_id__tournament"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__tournament_participation__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__tournament_participation")),
        sa.UniqueConstraint(
            "user_id",
            "tournament_id",
            name=op.f("uq__tournament_participation__user_id_tournament_id"),
        ),
    )
    op.create_table(
        "user_info",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("math_score", sa.Float(), nullable=True),
        sa.Column("language_score", sa.Float(), nullable=True),
        sa.Column("humanities_score", sa.Float(), nullable=True),
        sa.Column("science_score", sa.Float(), nullable=True),
        sa.Column(
            "average_score",
            sa.Float(),
            sa.Computed(
                "(math_score + language_score + humanities_score + science_score) / 4",
            ),
            nullable=True,
        ),
        sa.Column("dynamic_score", sa.Float(), nullable=False),
        sa.Column("duel_score", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__user_info__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_info")),
        sa.UniqueConstraint("user_id", name=op.f("uq__user_info__user_id")),
    )
    op.create_table(
        "user_web_socket_info",
        sa.Column(
            "last_websocket_connection", sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column(
            "last_websocket_disconnection", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__user_web_socket_info__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_web_socket_info")),
        sa.UniqueConstraint("user_id", name=op.f("uq__user_web_socket_info__user_id")),
    )
    op.create_table(
        "extracted_text",
        sa.Column("extraction_method", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("essay_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["essay_id"],
            ["essay.id"],
            name=op.f("fk__extracted_text__essay_id__essay"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__extracted_text")),
    )
    op.create_table(
        "feedback",
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("grade", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("feedback_category_id", sa.Integer(), nullable=False),
        sa.Column("essay_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["essay_id"],
            ["essay.id"],
            name=op.f("fk__feedback__essay_id__essay"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feedback_category_id"],
            ["feedback_category.id"],
            name=op.f("fk__feedback__feedback_category_id__feedback_category"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__feedback")),
    )
    op.create_table(
        "round",
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("duel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["duel_id"],
            ["session.id"],
            name=op.f("fk__round__duel_id__session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__round")),
    )
    op.create_table(
        "session_participation",
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("duel_score_change", sa.Float(), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk__session_participation__session_id__session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__session_participation__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__session_participation")),
    )
    op.create_table(
        "session_question",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk__session_question__question_id__question"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk__session_question__session_id__session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__session_question")),
        sa.UniqueConstraint(
            "session_id", "order", name=op.f("uq__session_question__session_id_order")
        ),
        sa.UniqueConstraint(
            "session_id",
            "question_id",
            name=op.f("uq__session_question__session_id_question_id"),
        ),
    )
    op.create_table(
        "session_question_user",
        sa.Column("submitted_text", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("grade", sa.Float(), nullable=True),
        sa.Column("timed_out", sa.Boolean(), nullable=False),
        sa.Column("session_question_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("choice_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (choice_id IS NOT NULL AND submitted_text = '' AND timed_out = false) OR\n            (choice_id IS NULL AND submitted_text != '' AND timed_out = false) OR\n            (choice_id IS NULL AND submitted_text = '')\n            ",
            name=op.f(
                "ck__session_question_user__check_session_question_answer_valid_states"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["choice.id"],
            name=op.f("fk__session_question_user__choice_id__choice"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_question.id"],
            name=op.f(
                "fk__session_question_user__session_question_id__session_question"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__session_question_user__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__session_question_user")),
        sa.UniqueConstraint(
            "session_question_id",
            "user_id",
            name=op.f("uq__session_question_user__session_question_id_user_id"),
        ),
    )
    op.create_table(
        "turn",
        sa.Column(
            "phase", sa.Enum("ATTACK", "DEFENSE", name="duelturnphase"), nullable=False
        ),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
            name=op.f("fk__turn__round_id__round"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__turn__user_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__turn")),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO "user" (username, email, phone_number, hashed_password, is_superuser, 
                           education_level, is_premium, commitment, balance, is_bot, 
                           bot_difficulty, signup_source)
        VALUES ('system', 'system@example.com', '21999202122', '', 
                false, 'UNKNOWN', false, 0, 0, false,
                NULL, 'OTHER'),
                ('pico', 'pico@example.com', '21999202123', '', 
                false, 'UNKNOWN', false, 0, 0, false,
                NULL, 'OTHER'),
                ('deleted', 'deleted@example.com', '21999202124', '', 
                false, 'UNKNOWN', false, 0, 0, false,
                NULL, 'OTHER');
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn")
    op.drop_table("session_question_user")
    op.drop_table("session_question")
    op.drop_table("session_participation")
    op.drop_table("round")
    op.drop_table("feedback")
    op.drop_table("extracted_text")
    op.drop_table("user_web_socket_info")
    op.drop_table("user_info")
    op.drop_table("tournament_participation")
    op.drop_table("session")
    op.drop_table("essay")
    op.drop_table("currency_transaction")
    op.drop_table("choice")
    op.drop_index("ix_user_username_lower", table_name="user")
    op.drop_index("ix_user_email_lower", table_name="user")
    op.drop_table("user")
    op.drop_table("tournament_prize")
    op.drop_table("question")
    op.drop_table("feedback_category")
    op.drop_table("course_college")
    op.drop_table("tournament")
    op.drop_index(
        "unique_inep_code",
        table_name="school",
        postgresql_where=sa.text("inep_code != ''"),
    )
    op.drop_table("school")
    op.drop_table("file")
    op.drop_table("essay_type")
    op.drop_table("essay_topic")
    op.drop_table("entity_association")
    op.drop_index("unique_default_currency_per_action_type", table_name="currency")
    op.drop_table("currency")
    op.drop_table("course")
    op.drop_table("college")
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS educationlevel")
    op.execute("DROP TYPE IF EXISTS questiontype")
    op.execute("DROP TYPE IF EXISTS quiztype")
    op.execute("DROP TYPE IF EXISTS questionselectionmethod")
    op.execute("DROP TYPE IF EXISTS duelstatus")
    op.execute("DROP TYPE IF EXISTS duelturnphase")
    op.execute("DROP TYPE IF EXISTS tournamentstatus")
    op.execute("DROP TYPE IF EXISTS currencyaction")
    op.execute("DROP TYPE IF EXISTS currencytype")
    op.execute("DROP TYPE IF EXISTS signupsource")
