"""morestuff

Revision ID: 11f22c234e67
Revises: 43d5d53cdf08
Create Date: 2025-06-07 14:45:42.632830

"""

from typing import Sequence, Union

import geoalchemy2.types
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11f22c234e67"
down_revision: Union[str, None] = "43d5d53cdf08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subtitle", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__community")),
        sa.UniqueConstraint(
            "name", "subtitle", name=op.f("uq__community__name_subtitle")
        ),
    )
    op.create_table(
        "community_user",
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["community.id"],
            name=op.f("fk__community_user__community_id__community"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__community_user__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__community_user")),
        sa.UniqueConstraint(
            "community_id",
            "user_id",
            name=op.f("uq__community_user__community_id_user_id"),
        ),
    )
    op.create_table(
        "in_app_notification",
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("in_app_notification_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_url", sa.Text(), nullable=False),
        sa.Column("flow_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__in_app_notification__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__in_app_notification__user_id__user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__in_app_notification")),
    )
    op.add_column(
        "institution",
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "institution",
        sa.Column("administrative_category", sa.String(length=50), nullable=True),
    )
    op.alter_column(
        "institution", "inep_code", existing_type=sa.VARCHAR(length=40), nullable=False
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER');
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_institution_location", table_name="institution", postgresql_using="gist"
    )
    op.alter_column(
        "institution", "inep_code", existing_type=sa.VARCHAR(length=40), nullable=True
    )
    op.drop_column("institution", "administrative_category")
    op.drop_column("institution", "location")
    op.drop_table("in_app_notification")
    op.drop_table("community_user")
    op.drop_table("community")
    # ### end Alembic commands ###
