"""country code to country id on foreign keys

Revision ID: 191b025420bb
Revises: 8564a87eca44
Create Date: 2025-06-17 08:44:20.846823

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "191b025420bb"
down_revision: str | None = "8564a87eca44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###

    # Migrate exam table
    op.add_column("exam", sa.Column("country_id", sa.Integer(), nullable=True))
    op.execute(
        sa.text("""
        UPDATE exam 
        SET country_id = country.id 
        FROM country 
        WHERE exam.country_code = country.code
    """)
    )
    op.alter_column("exam", "country_id", nullable=False)
    op.drop_constraint(
        op.f("fk__exam__country_code__country"), "exam", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__exam__country_id__country"), "exam", "country", ["country_id"], ["id"]
    )
    op.drop_column("exam", "country_code")

    # Migrate institution table
    op.add_column("institution", sa.Column("country_id", sa.Integer(), nullable=True))
    op.execute(
        sa.text("""
        UPDATE institution 
        SET country_id = country.id 
        FROM country 
        WHERE institution.country_code = country.code
    """)
    )
    op.alter_column("institution", "country_id", nullable=False)
    op.drop_index(
        op.f("unique_government_code_per_country"),
        table_name="institution",
        postgresql_where="((government_issued_code)::text <> ''::text)",
    )
    op.create_index(
        "unique_government_code_per_country",
        "institution",
        ["government_issued_code", "country_id"],
        unique=True,
        postgresql_where=sa.text("government_issued_code != ''"),
    )
    op.drop_constraint(
        op.f("fk__institution__country_code__country"),
        "institution",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__institution__country_id__country"),
        "institution",
        "country",
        ["country_id"],
        ["id"],
    )
    op.drop_column("institution", "country_code")

    # Migrate level_stage table
    op.add_column("level_stage", sa.Column("country_id", sa.Integer(), nullable=True))
    op.execute(
        sa.text("""
        UPDATE level_stage 
        SET country_id = country.id 
        FROM country 
        WHERE level_stage.country_code = country.code
    """)
    )
    op.drop_constraint(
        op.f("unique_level_stage_per_country"), "level_stage", type_="unique"
    )
    op.create_unique_constraint(
        "unique_level_stage_per_country",
        "level_stage",
        ["name", "level_id", "country_id"],
    )
    op.drop_constraint(
        op.f("fk__level_stage__country_code__country"),
        "level_stage",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__level_stage__country_id__country"),
        "level_stage",
        "country",
        ["country_id"],
        ["id"],
    )
    op.drop_column("level_stage", "country_code")

    # Migrate question_area table
    op.add_column("question_area", sa.Column("country_id", sa.Integer(), nullable=True))
    op.execute(
        sa.text("""
        UPDATE question_area 
        SET country_id = country.id 
        FROM country 
        WHERE question_area.country_code = country.code
    """)
    )
    op.alter_column("question_area", "country_id", nullable=False)
    op.drop_constraint(
        op.f("fk__question_area__country_code__country"),
        "question_area",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__question_area__country_id__country"),
        "question_area",
        "country",
        ["country_id"],
        ["id"],
    )
    op.drop_column("question_area", "country_code")

    # Migrate user table
    op.add_column("user", sa.Column("country_id", sa.Integer(), nullable=True))
    op.execute(
        sa.text("""
        UPDATE "user" 
        SET country_id = country.id 
        FROM country 
        WHERE "user".country_code = country.code
    """)
    )
    op.drop_constraint(
        op.f("fk__user__country_code__country"), "user", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__user__country_id__country"), "user", "country", ["country_id"], ["id"]
    )
    op.drop_column("user", "country_code")
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Downgrade user table
    op.add_column(
        "user",
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        sa.text("""
        UPDATE "user" 
        SET country_code = country.code 
        FROM country 
        WHERE "user".country_id = country.id
    """)
    )
    op.drop_constraint(
        op.f("fk__user__country_id__country"), "user", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__user__country_code__country"),
        "user",
        "country",
        ["country_code"],
        ["code"],
    )
    op.drop_column("user", "country_id")

    # Downgrade question_area table
    op.add_column(
        "question_area",
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        sa.text("""
        UPDATE question_area 
        SET country_code = country.code 
        FROM country 
        WHERE question_area.country_id = country.id
    """)
    )
    op.alter_column("question_area", "country_code", nullable=False)
    op.drop_constraint(
        op.f("fk__question_area__country_id__country"),
        "question_area",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__question_area__country_code__country"),
        "question_area",
        "country",
        ["country_code"],
        ["code"],
    )
    op.drop_column("question_area", "country_id")

    # Downgrade level_stage table
    op.add_column(
        "level_stage",
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        sa.text("""
        UPDATE level_stage 
        SET country_code = country.code 
        FROM country 
        WHERE level_stage.country_id = country.id
    """)
    )
    op.drop_constraint(
        op.f("fk__level_stage__country_id__country"), "level_stage", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__level_stage__country_code__country"),
        "level_stage",
        "country",
        ["country_code"],
        ["code"],
    )
    op.drop_constraint("unique_level_stage_per_country", "level_stage", type_="unique")
    op.create_unique_constraint(
        op.f("unique_level_stage_per_country"),
        "level_stage",
        ["name", "level_id", "country_code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("level_stage", "country_id")

    # Downgrade institution table
    op.add_column(
        "institution",
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        sa.text("""
        UPDATE institution 
        SET country_code = country.code 
        FROM country 
        WHERE institution.country_id = country.id
    """)
    )
    op.alter_column("institution", "country_code", nullable=False)
    op.drop_constraint(
        op.f("fk__institution__country_id__country"), "institution", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__institution__country_code__country"),
        "institution",
        "country",
        ["country_code"],
        ["code"],
    )
    op.drop_index(
        "unique_government_code_per_country",
        table_name="institution",
        postgresql_where=sa.text("government_issued_code != ''"),
    )
    op.create_index(
        op.f("unique_government_code_per_country"),
        "institution",
        ["government_issued_code", "country_code"],
        unique=True,
        postgresql_where="((government_issued_code)::text <> ''::text)",
    )
    op.drop_column("institution", "country_id")

    # Downgrade exam table
    op.add_column(
        "exam",
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        sa.text("""
        UPDATE exam 
        SET country_code = country.code 
        FROM country 
        WHERE exam.country_id = country.id
    """)
    )
    op.alter_column("exam", "country_code", nullable=False)
    op.drop_constraint(
        op.f("fk__exam__country_id__country"), "exam", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk__exam__country_code__country"),
        "exam",
        "country",
        ["country_code"],
        ["code"],
    )
    op.drop_column("exam", "country_id")
    # ### end Alembic commands ###
