"""cannot set null for level id on education info

Revision ID: 8564a87eca44
Revises: f75786c398b3
Create Date: 2025-06-15 17:16:12.659108

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8564a87eca44"
down_revision: Union[str, None] = "f75786c398b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__education_info__level_id__education_level"),
        "education_info",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__education_info__level_id__education_level"),
        "education_info",
        "education_level",
        ["level_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__education_info__level_id__education_level"),
        "education_info",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__education_info__level_id__education_level"),
        "education_info",
        "education_level",
        ["level_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
