"""user country not required

Revision ID: 835e3554f78b
Revises: 283b2bc70b03
Create Date: 2025-06-12 11:03:30.753063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.base
import app.localization
import pgvector.sqlalchemy
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision: str = '835e3554f78b'
down_revision: Union[str, None] = '283b2bc70b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
    
    # Only execute this code if it's the first migration
    if not down_revision:
        with open("app/countries/countries.sql", "r") as f:
            op.execute(f.read())
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, country_code, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 'BR', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
