"""flow feed scoring

Revision ID: 0c9931af6475
Revises: 4db3ea22798e
Create Date: 2025-07-18 16:43:31.278840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c9931af6475"
down_revision: Union[str, None] = "4db3ea22798e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_feed_score_group_type",
        sa.Column(
            "group_type",
            sa.Enum(
                "COMMUNITY",
                "INTENDED_EDUCATION",
                "INTENDED_COURSE",
                "INSTITUTION",
                "INSTITUTION_TYPE",
                "STAGE",
                "COURSE",
                name="flowfeedscoregrouptypeenum",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_feed_score_group_type")),
        sa.UniqueConstraint(
            "group_type", name=op.f("uq__flow_feed_score_group_type__group_type")
        ),
    )
    op.create_table(
        "flow_feed_score",
        sa.Column("flow_id", sa.Integer(), nullable=False),
        sa.Column("group_type_id", sa.Integer(), nullable=False),
        sa.Column("group_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flow.id"],
            name=op.f("fk__flow_feed_score__flow_id__flow"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_type_id"],
            ["flow_feed_score_group_type.id"],
            name=op.f("fk__flow_feed_score__group_type_id__flow_feed_score_group_type"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__flow_feed_score")),
    )
    op.create_index(
        op.f("ix__flow_feed_score__group_type_id_flow_id_group_key"),
        "flow_feed_score",
        ["group_type_id", "flow_id", "group_key"],
        unique=True,
    )
    op.alter_column(
        "flow",
        "is_ready",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flow",
        "is_ready",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix__flow_feed_score__group_type_id_flow_id_group_key"),
        table_name="flow_feed_score",
    )
    op.drop_table("flow_feed_score")
    op.drop_table("flow_feed_score_group_type")
    # ### end Alembic commands ###
