"""changing online info

Revision ID: f75786c398b3
Revises: f768ee9f2fae
Create Date: 2025-06-13 17:32:54.481493

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f75786c398b3"
down_revision: Union[str, None] = "f768ee9f2fae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only execute this code if it's the first migration
    if not down_revision:
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__user_websocket_info__user_id"), "user_websocket_info", type_="unique"
    )
    op.rename_table("user_websocket_info", "user_online_info")
    op.add_column(
        "user_online_info",
        sa.Column("is_online", sa.Boolean(), nullable=False, default=False),
    )
    op.create_unique_constraint(
        op.f("uq__user_online_info__user_id"), "user_online_info", ["user_id"]
    )
    # ### end Alembic commands ###

    # Only execute this code if it's the first migration
    if not down_revision:
        with open("app/countries/countries.sql", "r") as f:
            op.execute(f.read())
        op.execute(
            """
            INSERT INTO "user" (username, name, email, phone_number, hashed_password, is_superuser, is_bot, bot_difficulty, signup_source, country_code, social_score, xp_score)
            VALUES ('deleted', 'deleted', 'deleted@example.com', '21999202124', '', false, false, NULL, 'OTHER', 'BR', 0, 0);
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__user_online_info__user_id"), "user_online_info", type_="unique"
    )
    op.drop_column("user_online_info", "is_online")
    op.rename_table("user_online_info", "user_websocket_info")
    op.create_unique_constraint(
        op.f("uq__user_websocket_info__user_id"),
        "user_websocket_info",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
