"""All models

Revision ID: ba4484b8b83b
Revises:
Create Date: 2025-02-23 13:04:20.902988

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba4484b8b83b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatroom",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__chatroom")),
        sa.UniqueConstraint("name", name=op.f("uq__chatroom__name")),
    )
    op.create_table(
        "college",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__college")),
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course")),
    )
    op.create_table(
        "school",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__school")),
    )
    op.create_table(
        "course_college",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("college_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["college.id"],
            name=op.f("fk__course_college__college_id__college"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk__course_college__course_id__course"),
        ),
        sa.PrimaryKeyConstraint(
            "course_id", "college_id", name=op.f("pk__course_college")
        ),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column(
            "education_level",
            sa.Enum(
                "MIDDLE_SCHOOL",
                "FIRST_YEAR_HIGH_SCHOOL",
                "SECOND_YEAR_HIGH_SCHOOL",
                "THIRD_YEAR_HIGH_SCHOOL",
                "HIGH_SCHOOL_COMPLETE",
                "COLLEGE",
                "UNKNOWN",
                name="educationlevel",
            ),
            nullable=False,
        ),
        sa.Column("chosen_college_id", sa.Integer(), nullable=True),
        sa.Column("chosen_course_id", sa.Integer(), nullable=True),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("commitment", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("bot_difficulty", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "is_bot = False AND bot_difficulty IS NULL OR is_bot = True AND bot_difficulty IS NOT NULL",
            name=op.f("ck__user__bot_difficulty_check"),
        ),
        sa.ForeignKeyConstraint(
            ["chosen_college_id"],
            ["college.id"],
            name=op.f("fk__user__chosen_college_id__college"),
        ),
        sa.ForeignKeyConstraint(
            ["chosen_course_id"],
            ["course.id"],
            name=op.f("fk__user__chosen_course_id__course"),
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_id"], ["user.id"], name=op.f("fk__user__referred_by_id__user")
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name=op.f("fk__user__school_id__school")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
        sa.UniqueConstraint("email", name=op.f("uq__user__email")),
        sa.UniqueConstraint("phone_number", name=op.f("uq__user__phone_number")),
        sa.UniqueConstraint("username", name=op.f("uq__user__username")),
    )
    op.create_index(
        "ix_user_username_lower", "user", [sa.text("lower(username)")], unique=True
    )
    op.create_table(
        "membership",
        sa.Column("chatroom_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chatroom_id"],
            ["chatroom.id"],
            name=op.f("fk__membership__chatroom_id__chatroom"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__membership__user_id__user")
        ),
        sa.PrimaryKeyConstraint("chatroom_id", "user_id", name=op.f("pk__membership")),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chatroom_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chatroom_id"],
            ["chatroom.id"],
            name=op.f("fk__message__chatroom_id__chatroom"),
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["user.id"], name=op.f("fk__message__sender_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__message")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_table("membership")
    op.drop_index("ix_user_username_lower", table_name="user")
    op.drop_table("user")
    op.drop_table("course_college")
    op.drop_table("school")
    op.drop_table("course")
    op.drop_table("college")
    op.drop_table("chatroom")
    op.execute("DROP TYPE educationlevel")
    # ### end Alembic commands ###
