# Generated by Django 5.0.1 on 2024-01-28 01:48

from api.models import (
    DELETED_EMAIL,
    DELETED_PHONE_NUMBER,
    DELETED_USERNAME,
    PICO_EMAIL,
    PICO_PHONE_NUMBER,
    PICO_USERNAME,
    SYSTEM_EMAIL,
    SYSTEM_PHONE_NUMBER,
    SYSTEM_USERNAME,
)
from django.db import migrations


def create_sentinel_user(apps, schema_editor, username, phone_number, email):
    User = apps.get_model("api", "User")
    User.objects.get_or_create(
        username=username,
        defaults={
            "phone_number": phone_number,
            "email": email,
            "is_active": False,
        },
    )


def delete_sentinel_user(apps, schema_editor, username, phone_number, email):
    User = apps.get_model("api", "User")
    sentinel_user = User.objects.get(
        username=username,
        phone_number=phone_number,
        email=email,
    )
    sentinel_user.delete()


def create_deleted_user(apps, schema_editor):
    create_sentinel_user(
        apps,
        schema_editor,
        DELETED_USERNAME,
        DELETED_PHONE_NUMBER,
        DELETED_EMAIL,
    )


def delete_deleted_user(apps, schema_editor):
    delete_sentinel_user(
        apps,
        schema_editor,
        DELETED_USERNAME,
        DELETED_PHONE_NUMBER,
        DELETED_EMAIL,
    )


def create_pico_user(apps, schema_editor):
    create_sentinel_user(
        apps,
        schema_editor,
        PICO_USERNAME,
        PICO_PHONE_NUMBER,
        PICO_EMAIL,
    )


def delete_pico_user(apps, schema_editor):
    delete_sentinel_user(
        apps,
        schema_editor,
        PICO_USERNAME,
        PICO_PHONE_NUMBER,
        PICO_EMAIL,
    )


def create_system_user(apps, schema_editor):
    create_sentinel_user(
        apps,
        schema_editor,
        SYSTEM_USERNAME,
        SYSTEM_PHONE_NUMBER,
        SYSTEM_EMAIL,
    )


def delete_system_user(apps, schema_editor):
    delete_sentinel_user(
        apps,
        schema_editor,
        SYSTEM_USERNAME,
        SYSTEM_PHONE_NUMBER,
        SYSTEM_EMAIL,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_deleted_user, delete_deleted_user),
        migrations.RunPython(create_pico_user, delete_pico_user),
        migrations.RunPython(create_system_user, delete_system_user),
    ]
