# Generated by Django 5.0.3 on 2024-03-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatroom_icon'),
        ('api', '0006_message_essay_topic'),
    ]

    operations = [
    ]
