# Generated by Django 5.1.2 on 2024-12-12 02:27

import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_user_education_level"),
        ("quiz", "0029_add_session_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="quiz.session",
            ),
        ),
    ]
