# Generated by Django 5.1.6 on 2025-02-18 12:04

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def migrate_schools(apps, schema_editor):
    User = apps.get_model("api", "User")
    School = apps.get_model("api", "School")

    # Get all distinct school values
    distinct_schools = User.objects.values_list("school", flat=True).distinct()

    # Create School objects for each distinct value
    school_mapping: dict[str, Any] = {}
    for school_name in distinct_schools:
        if school_name:  # Only create for non-null values
            school = School.objects.create(
                name=school_name,
                user_submitted=True,  # Since these were user-submitted previously
            )
            school_mapping[school_name] = school

    # Update all users to point to the new School objects
    for user in User.objects.all():
        if user.school:  # Only update if school is not null
            user.school_new_id = school_mapping[user.school].id
            user.save()


def reverse_migrate_schools(apps, schema_editor):
    User = apps.get_model("api", "User")
    School = apps.get_model("api", "School")

    # Convert back to storing school name directly
    for user in User.objects.select_related("school_new").all():
        if user.school_new:
            user.school = user.school_new.name
            user.save()

    # Delete all School objects
    School.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_auto_20250217_1335"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("user_submitted", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="school_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.school",
            ),
        ),
        migrations.RunPython(migrate_schools, reverse_migrate_schools),
        migrations.RenameField(
            model_name="user",
            old_name="school",
            new_name="school_old",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="school_new",
            new_name="school",
        ),
        migrations.RemoveField(
            model_name="user",
            name="school_old",
        ),
    ]
