# Generated by Django 5.0.6 on 2024-06-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO quiz_question (
                id,
                text,
                embedding,
                source,
                created_at,
                answer_text,
                image,
                answer_image,
                subject,
                extra_embedding_text
            )
            SELECT
                id,
                text,
                embedding,
                source,
                created_at,
                answer_text,
                image,
                answer_image,
                subject,
                extra_embedding_text
            FROM
                core_question;
            SELECT setval(pg_get_serial_sequence('"quiz_question"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "quiz_question";
            """,
            reverse_sql="""
            INSERT INTO core_question (
                id,
                text,
                embedding,
                source,
                created_at,
                answer_text,
                image,
                answer_image,
                subject,
                extra_embedding_text
            )
            SELECT
                id,
                text,
                embedding,
                source,
                created_at,
                answer_text,
                image,
                answer_image,
                subject,
                extra_embedding_text
            FROM
                quiz_question;
            SELECT setval(pg_get_serial_sequence('"core_question"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_question";
            """,
        ),
    ]
