# Generated by Django 5.0.6 on 2024-06-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_auto_20240611_1836"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO quiz_choice (
                id,
                text,
                is_correct,
                question_id,
                _order
            )
            SELECT
                id,
                text,
                is_correct,
                question_id,
                _order
            FROM
                core_choice;
            SELECT setval(pg_get_serial_sequence('"quiz_choice"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "quiz_choice";
            """,
            reverse_sql="""
            INSERT INTO core_choice (
                id,
                text,
                is_correct,
                question_id,
                _order
            )
            SELECT
                id,
                text,
                is_correct,
                question_id,
                _order
            FROM
                quiz_choice;
            SELECT setval(pg_get_serial_sequence('"core_choice"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_choice";
            """,
        ),
    ]
