# Generated by Django 5.0.6 on 2024-06-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_auto_20240612_0636"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO quiz_quiz (
                id,
                created_at,
                query,
                area,
                file,
                source_filter
            )
            SELECT
                id,
                created_at,
                query,
                area,
                file,
                source_filter
            FROM
                core_quiz;
            SELECT setval(pg_get_serial_sequence('"quiz_quiz"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "quiz_quiz";
            """,
            reverse_sql="""
            INSERT INTO core_quiz (
                id,
                created_at,
                query,
                area,
                file,
                source_filter
            )
            SELECT
                id,
                created_at,
                query,
                area,
                file,
                source_filter
            FROM
                quiz_quiz;
            SELECT setval(pg_get_serial_sequence('"core_quiz"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_quiz";
            """,
        ),
    ]
