# Generated by Django 5.0.6 on 2024-06-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_auto_20240612_0656"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO quiz_userquiz (
                id,
                start_time,
                quiz_id,
                user_id
            )
            SELECT
                id,
                start_time,
                quiz_id,
                user_id
            FROM
                core_userquiz;
            SELECT setval(pg_get_serial_sequence('"quiz_userquiz"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "quiz_userquiz";
            """,
            reverse_sql="""
            INSERT INTO core_userquiz (
                id,
                start_time,
                quiz_id,
                user_id
            )
            SELECT
                id,
                start_time,
                quiz_id,
                user_id
            FROM
                quiz_userquiz;
            SELECT setval(pg_get_serial_sequence('"core_userquiz"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_userquiz";
            """,
        ),
    ]
