# Generated by Django 5.0.6 on 2024-06-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_auto_20240612_0656"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO quiz_userquizanswer (
                id,
                choice_id,
                question_id,
                timestamp,
                user_quiz_id
            )
            SELECT
                id,
                choice_id,
                question_id,
                timestamp,
                user_quiz_id
            FROM
                core_userquizanswer;
            SELECT setval(pg_get_serial_sequence('"quiz_userquizanswer"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "quiz_userquizanswer";
            """,
            reverse_sql="""
            INSERT INTO core_userquizanswer (
                id,
                choice_id,
                question_id,
                timestamp,
                user_quiz_id
            )
            SELECT
                id,
                choice_id,
                question_id,
                timestamp,
                user_quiz_id
            FROM
                quiz_userquizanswer;
            SELECT setval(pg_get_serial_sequence('"core_userquizanswer"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_userquizanswer";
            """,
        ),
    ]
