# Generated by Django 5.0.6 on 2024-08-03 01:20

import logging

import django.db.models.expressions
from asgiref.sync import async_to_sync
from django.db import migrations, models, transaction

logger = logging.getLogger(__name__)

AVERAGE_SCORES_BY_CORRECT_QUESTIONS = {
    "Matemática": {
        0: 34.807715700423515,
        1: 340.3919083506703,
        2: 347.89110952590715,
        3: 356.6644923843018,
        4: 365.6806442847766,
        5: 376.6495329440993,
        6: 388.75168599312383,
        7: 402.5552168692767,
        8: 418.54404171977853,
        9: 436.2170585175776,
        10: 456.18579764446713,
        11: 477.84811746538753,
        12: 500.9606017320928,
        13: 525.0945914584463,
        14: 549.5376122089915,
        15: 573.2045449602232,
        16: 596.0457199654866,
        17: 617.2752798020813,
        18: 636.7839696022658,
        19: 654.5168317882682,
        20: 670.7696447824048,
        21: 685.4581055321551,
        22: 699.1704472989638,
        23: 712.0733215273386,
        24: 724.2709679549494,
        25: 736.0861546375147,
        26: 747.4312282565551,
        27: 758.5698012147933,
        28: 769.3615211958942,
        29: 780.1804656500949,
        30: 790.5812965416326,
        31: 801.1644378846144,
        32: 811.6804640737591,
        33: 822.7527862343604,
        34: 834.0897018955641,
        35: 845.4453306713574,
        36: 857.3612294553665,
        37: 870.3484997697327,
        38: 883.3107494269004,
        39: 897.6048632485632,
        40: 909.9874502156779,
        41: 924.0223210962217,
        42: 937.3937008963151,
        43: 952.1557160532905,
        44: 957.4090083798883,
        45: 958.5999999999999,
    },
    "Linguagens": {
        0: 59.92813425468904,
        1: 295.0369318181818,
        2: 303.5585416666667,
        3: 313.3879356568365,
        4: 321.50502606105726,
        5: 332.8778207607996,
        6: 344.5993752055245,
        7: 357.5448717336264,
        8: 370.3574103648035,
        9: 384.3338262476895,
        10: 398.4996255069462,
        11: 412.40422234621275,
        12: 426.3274695939476,
        13: 439.45747401148475,
        14: 452.220138989431,
        15: 463.9064262407075,
        16: 475.3085441346369,
        17: 485.8985721519829,
        18: 495.88787091325474,
        19: 505.2466637164582,
        20: 514.1750748400317,
        21: 522.8061935253203,
        22: 531.0514834783186,
        23: 539.1695330334362,
        24: 547.1359077240385,
        25: 555.0231924305946,
        26: 562.9001464237391,
        27: 570.7914789756808,
        28: 578.8674598994,
        29: 586.9907129466317,
        30: 595.3531732397627,
        31: 603.8596089581199,
        32: 612.7671792503658,
        33: 622.0172330140705,
        34: 631.6121976436125,
        35: 641.8813018524061,
        36: 652.7779885200896,
        37: 664.3143005232502,
        38: 676.8008908194066,
        39: 690.1132677834428,
        40: 704.6289226642825,
        41: 720.7025233644861,
        42: 738.233167082294,
        43: 758.3923076923077,
        44: 787.2314285714288,
        45: 820.8,
    },
    "Ciências da Natureza": {
        0: 29.267773397416455,
        1: 353.22112075096004,
        2: 362.5068104872006,
        3: 372.39011905646385,
        4: 382.57155021185815,
        5: 393.30317410733323,
        6: 404.2822959835389,
        7: 416.25570336562515,
        8: 428.97994750006274,
        9: 442.9976782651157,
        10: 457.9752478249329,
        11: 473.9909344423269,
        12: 490.8343736300752,
        13: 508.2356105118635,
        14: 525.9084305864985,
        15: 543.2198760938893,
        16: 559.9812166134545,
        17: 575.8116052850603,
        18: 590.2167400992596,
        19: 603.5716963423911,
        20: 615.5749160482922,
        21: 626.4210934772,
        22: 636.3983910399741,
        23: 645.6981611144041,
        24: 654.2706998027236,
        25: 662.5222341569843,
        26: 670.5698713488475,
        27: 678.0319579535154,
        28: 685.9100591716369,
        29: 693.0979091719747,
        30: 700.9080295717051,
        31: 708.4732429699254,
        32: 716.1872278018097,
        33: 724.2719205550065,
        34: 732.3434484622268,
        35: 740.7131647447382,
        36: 749.8774633808209,
        37: 758.4258651700577,
        38: 767.9671256684492,
        39: 778.9821926251925,
        40: 790.1534922429496,
        41: 803.5040380638234,
        42: 815.630423206278,
        43: 840.6093540051679,
        44: 856.9464285714287,
        45: 871.8499999999999,
    },
    "Ciências Humanas": {
        0: 30.109506489405035,
        1: 307.9161497306509,
        2: 317.4222303326218,
        3: 325.3524559791025,
        4: 334.25132472550814,
        5: 344.10214360077623,
        6: 354.6185005252918,
        7: 367.0927267076933,
        8: 380.3033615877154,
        9: 394.4006241389825,
        10: 409.15937230455506,
        11: 424.190662888397,
        12: 439.2457902967784,
        13: 453.89427351385797,
        14: 467.795610788304,
        15: 481.20537507694496,
        16: 493.7971018091955,
        17: 505.5747375149165,
        18: 516.5666143868707,
        19: 526.8779918934777,
        20: 536.6318375634773,
        21: 545.8940356475894,
        22: 554.5724748054347,
        23: 563.040454732276,
        24: 571.223090235834,
        25: 579.1405521514985,
        26: 587.134943993899,
        27: 594.9168155431378,
        28: 602.7281224585354,
        29: 610.6124820589686,
        30: 618.6368526013555,
        31: 626.8700691009474,
        32: 635.1900980671244,
        33: 644.0492054187391,
        34: 653.1421869758951,
        35: 662.6863012439338,
        36: 673.0142705035366,
        37: 683.861567562773,
        38: 695.6110831708959,
        39: 708.3711827888692,
        40: 722.557635222006,
        41: 738.8440012628625,
        42: 758.2701507665801,
        43: 779.1142417933573,
        44: 801.4580910240202,
        45: 831.1000000000001,
    },
}


def get_question_area(question) -> str | None:
    for area, subjects in ENEM_AREAS.items():
        if question.subject in subjects:
            return area


ENEM_AREAS = {
    "Ciências Humanas": [
        "Filosofia",
        "Geografia",
        "História",
        "Sociologia",
    ],
    "Ciências da Natureza": [
        "Biologia",
        "Física",
        "Química",
    ],
    "Linguagens": [
        "Inglês",
        "Português",
        "Espanhol",
    ],
    "Matemática": ["Matemática"],
}


async def fetch_user_quiz_answers(apps, user) -> list:
    UserQuizAnswer = apps.get_model("quiz", "UserQuizAnswer")
    return [
        answer
        async for answer in UserQuizAnswer.objects.select_related(
            "user_quiz__user", "choice", "question"
        )
        .order_by("-timestamp")
        .filter(user_quiz__user=user)
    ]


def aggregate_user_scores(user_quiz_answers: list) -> dict:
    user_score = {
        "area_answers_for_score": {area: [] for area in ENEM_AREAS.keys()},
    }

    for answer in user_quiz_answers:
        area = get_question_area(answer.question)
        if area:
            if len(user_score["area_answers_for_score"][area]) < 45:
                user_score["area_answers_for_score"][area].append(answer)

    return user_score


def sum_correct_answers(answers: list) -> int:
    correct_answers = sum(1 for ans in answers if ans.choice.is_correct)
    return correct_answers


def get_area_expected_score(num_correct_questions: int, area: str) -> float:
    score = AVERAGE_SCORES_BY_CORRECT_QUESTIONS[area][num_correct_questions]
    return score


async def calc_user_stats(apps, user) -> dict:
    logger.debug("Starting to compute user statistics.")
    user_quiz_answers = await fetch_user_quiz_answers(apps, user)
    user_score = aggregate_user_scores(user_quiz_answers)

    area_expected_scores: dict[str, float] = {}
    for area, answers in user_score["area_answers_for_score"].items():
        num_correct_questions = sum_correct_answers(answers)
        area_expected_scores[area] = get_area_expected_score(
            num_correct_questions, area
        )

    result = {
        "id": user.id,
        "username": user.username,
        "area_expected_scores": area_expected_scores,
    }

    return result


async def update_score(apps, user):
    UserInfo = apps.get_model("quiz", "UserInfo")
    logger.debug(f"Updating score for user {user.username}.")

    area_expected_scores = (await calc_user_stats(apps, user))["area_expected_scores"]

    math_score = area_expected_scores["Matemática"]
    language_score = area_expected_scores["Linguagens"]
    humanities_score = area_expected_scores["Ciências Humanas"]
    science_score = area_expected_scores["Ciências da Natureza"]

    user_info, created = await UserInfo.objects.aget_or_create(
        user=user,
        defaults={
            "math_score": math_score,
            "language_score": language_score,
            "humanities_score": humanities_score,
            "science_score": science_score,
        },
    )

    if not created:
        user_info.math_score = math_score
        user_info.language_score = language_score
        user_info.humanities_score = humanities_score
        user_info.science_score = science_score
        await user_info.asave()

    logger.debug(
        f"User {user.username} math_score updated to {user_info.math_score}, language_score updated to {user_info.language_score}, humanities_score updated to {user_info.humanities_score}, science_score updated to {user_info.science_score}."
    )


def update_user_scores(apps, schema_editor):
    User = apps.get_model("api", "User")

    # Fetch all users
    users = User.objects.all()

    with transaction.atomic():
        for user in users:
            async_to_sync(update_score)(apps, user)


def noop(apps, schema_editor):
    # No-op function for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_userinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="score",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="humanities_score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="language_score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="math_score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="science_score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="average_score",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("math_score"), "+", models.F("language_score")
                            ),
                            "+",
                            models.F("humanities_score"),
                        ),
                        "+",
                        models.F("science_score"),
                    ),
                    "/",
                    models.Value(4),
                ),
                output_field=models.FloatField(),
            ),
        ),
        migrations.RunPython(update_user_scores, reverse_code=noop),
    ]
