# Generated by Django 5.1 on 2024-08-21 20:43

import api.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_quiz_unique_area_source_query_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.models.user.get_deleted_user), related_name='quizzes_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
