# Generated by Django 5.1 on 2024-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_quiz_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_resubmit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
