# Generated by Django 5.1 on 2024-09-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_choice_image_alter_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='caderno',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
