# Generated by Django 5.1.1 on 2024-09-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_question_caderno'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='unique_area_source_query_question_type',
        ),
    ]
