# Generated by Django 5.1.2 on 2024-10-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_quiz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
