# Generated by Django 5.1.2 on 2024-12-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20241217_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.session',),
        ),
    ]
