# Generated by Django 5.1.2 on 2024-12-24 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0035_sessionparticipation_alter_session_participants_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("session_type", "duel"), ("selection_method", ""), _connector="OR"
                ),
                name="non_duel_must_not_have_selection_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("session_type", "duel"), _negated=True),
                    (
                        "selection_method__in",
                        ["random_official", "query_official", "user_generated"],
                    ),
                    _connector="OR",
                ),
                name="duel_selection_method_must_be_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("session_type", "quiz"), _negated=True),
                    ("question_type__in", ["multiple_choice", "open_ended", "all"]),
                    _connector="OR",
                ),
                name="quiz_must_have_valid_question_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("session_type", "quiz"), _negated=True),
                    ("quiz_type__in", ["query", "personalized"]),
                    _connector="OR",
                ),
                name="quiz_must_have_valid_quiz_type",
            ),
        ),
    ]
