# Generated by Django 5.1.1 on 2024-12-27 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_session_non_duel_must_not_have_selection_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='quiz_must_have_valid_quiz_type',
        ),
        migrations.AlterField(
            model_name='session',
            name='quiz_type',
            field=models.CharField(blank=True, choices=[('query', 'Query-based'), ('personalized', 'Personalized'), ('custom', 'Custom'), ('', 'Not applicable')], default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session_type', 'quiz'), _negated=True), ('quiz_type__in', ['query', 'personalized', 'custom']), _connector='OR'), name='quiz_must_have_valid_quiz_type'),
        ),
    ]
