# Generated by Django 5.1.2 on 2025-01-01 00:30

from django.db import migrations


def migrate_duel_phase(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(session_type="duel").update(duel_phase="attack")


def migrate_current_turn_user(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    sessions = Session.objects.filter(session_type="duel").prefetch_related(
        "participants"
    )

    updates = []
    for session in sessions:
        first_participant = session.participants.first()
        if first_participant:
            updates.append((session.id, first_participant.id))

    if updates:
        # Update in bulk
        Session.objects.bulk_update(
            [
                Session(id=update[0], current_turn_user_id=update[1])
                for update in updates
            ],
            ["current_turn_user"],
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "quiz",
            "0040_remove_session_duel_fields_must_be_set_and_valid_if_duel_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            migrate_duel_phase, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            migrate_current_turn_user, reverse_code=migrations.RunPython.noop
        ),
    ]
