# Generated by Django 5.1.2 on 2025-01-08 01:16

import api.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0043_alter_sessionquestion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="current_turn_start_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="duel_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not applicable"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(api.models.user.get_deleted_user),
                related_name="sessions_winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
