# Generated by Django 5.1.2 on 2025-01-08 04:39

from django.db import migrations
from django.utils import timezone


def set_current_turn_start_time(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(session_type="duel").update(
        current_turn_start_time=timezone.now()
    )


def unset_current_turn_start_time(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(session_type="duel").update(current_turn_start_time=None)


def set_duel_status(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(session_type="duel").update(duel_status="in_progress")


def unset_duel_status(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(session_type="duel").update(duel_status="")


class Migration(migrations.Migration):
    dependencies = [
        (
            "quiz",
            "0044_remove_session_duel_fields_must_be_set_and_valid_if_duel_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            set_current_turn_start_time,
            unset_current_turn_start_time,
        ),
        migrations.RunPython(
            set_duel_status,
            unset_duel_status,
        ),
    ]
