# Generated by Django 5.1.2 on 2025-01-09 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_auto_20250108_0139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionquestionanswer',
            name='session_question_answer_choice_xor_submitted_text',
        ),
        migrations.AddConstraint(
            model_name='sessionquestionanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('choice__isnull', True), _negated=True), ('submitted_text__exact', '')), ('choice__isnull', True), _connector='OR'), name='session_question_answer_choice_xor_submitted_text'),
        ),
    ]
