# Generated by Django 5.1.4 on 2025-01-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_remove_session_duel_fields_must_be_set_and_valid_if_duel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_fast',
            field=models.BooleanField(default=False),
        ),
    ]
