# Generated by Django 5.1.5 on 2025-01-22 05:07

from django.db import migrations


def set_answers_timed_out(apps, schema_editor):
    # before, the convention was that if the user didnt answer in time, the answer exists, but choice_id and submitted_text are null
    # now, the convention is that if the user didnt answer in time, the answer exists, but choice_id and submitted_text are null, and timed_out is true
    # so we need to set timed_out to true for all answers where choice_id and submitted_text are null
    SessionQuestionAnswer = apps.get_model("quiz", "SessionQuestionAnswer")
    SessionQuestionAnswer.objects.filter(
        choice__isnull=True,
        submitted_text__isnull=True,
    ).update(timed_out=True)


class Migration(migrations.Migration):
    dependencies = [
        (
            "quiz",
            "0049_remove_sessionquestionanswer_session_question_answer_choice_xor_submitted_text_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            code=set_answers_timed_out,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
