# Generated by Django 5.1.5 on 2025-01-22 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0051_userinfo_duel_score_alter_userinfo_humanities_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SessionQuestionAnswer",
            new_name="SessionQuestionUser",
        ),
    ]
