# Generated by Django 5.1.5 on 2025-01-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_question_is_fast'),
        ('quiz', '0053_remove_sessionquestionuser_session_question_answer_valid_states_and_more'),
    ]

    operations = [
    ]
