# Generated by Django 5.1.5 on 2025-01-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_tournament_tournamentparticipation_and_more'),
        ('quiz', '0057_session_is_fast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='duel_fields_must_be_set_and_valid_if_duel',
        ),
        migrations.AddField(
            model_name='session',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='challenges.tournament'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_turn_start_time__isnull', False), ('duel_phase__in', ('attack', 'defense')), ('duel_status__in', ('in_progress', 'completed', 'abandoned')), ('n_questions_per_round__isnull', False), ('n_rounds__isnull', False), ('selection_method__in', ('random_official', 'query_official', 'user_generated')), ('session_type', 'duel')), models.Q(models.Q(('session_type', 'duel'), _negated=True), ('current_turn_start_time__isnull', True), ('current_turn_user__isnull', True), ('duel_phase', ''), ('duel_status', ''), ('n_questions_per_round__isnull', True), ('n_rounds__isnull', True), ('selection_method', ''), ('tournament__isnull', True), ('winner__isnull', True)), _connector='OR'), name='duel_fields_must_be_set_and_valid_if_duel'),
        ),
    ]
