# Generated by Django 5.1.6 on 2025-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0060_turn_remove_session_quiz_must_have_valid_types_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choice',
            name='choice_has_image_xor_text',
        ),
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='choices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, default='', upload_to='answers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='questions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='sessions/files/'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('image', ''), _negated=True), ('text', '')), models.Q(('image', ''), models.Q(('text', ''), _negated=True)), _connector='OR'), name='choice_has_image_xor_text'),
        ),
    ]
