# Generated by Django 5.1.6 on 2025-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0061_remove_choice_choice_has_image_xor_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dynamic_score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
