# Generated by Django 5.1.6 on 2025-03-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0062_userinfo_dynamic_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
