# Generated by Django 5.2 on 2025-05-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0063_session_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("block_number", models.PositiveIntegerField()),
                ("block_text", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcriptions",
                        to="quiz.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "block_number"],
                "unique_together": {("session", "block_number")},
            },
        ),
    ]
