# Generated by Django 5.2 on 2025-05-08 13:35

from django.conf import settings
from django.db import migrations, models


def update_quiz_selection_methods(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    # Update quizzes with quiz_type 'custom' to use 'user_generated' selection method
    Session.objects.filter(session_type="quiz", quiz_type="custom").update(
        selection_method="user_generated"
    )
    # Update quizzes with quiz_type 'query' to use 'query_official' selection method
    Session.objects.filter(session_type="quiz", quiz_type="query").update(
        selection_method="query_official"
    )

    # if any quiz still has selection method not applicable, set it to query_official
    Session.objects.filter(selection_method="").update(
        selection_method="query_official"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_tournament_tournamentparticipation_and_more"),
        ("quiz", "0064_transcription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="duel_challenge_selection_method_valid",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="non_duel_challenge_selection_method_valid",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="challenge_start_end_time_valid",
        ),
        migrations.AddField(
            model_name="session",
            name="question_density",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not applicable"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="selection_source",
            field=models.CharField(
                blank=True,
                choices=[("random", "Random"), ("topic", "Topic"), ("files", "Files")],
                default="topic",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="topic",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="session",
            name="selection_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("random_official", "Random official"),
                    ("query_official", "Query official"),
                    ("user_generated", "User-generated"),
                    ("full", "Full"),
                ],
                default="query_official",
                max_length=25,
            ),
        ),
        migrations.RunPython(update_quiz_selection_methods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "selection_method__in",
                        ("random_official", "query_official", "user_generated", "full"),
                    )
                ),
                name="selection_method_valid",
            ),
        ),
    ]
