[pytest]
addopts = --show-capture=stdout --capture=tee-sys
pythonpath = . ./app
testpaths = tests
filterwarnings =
    ignore:Object of type <User> not in session, add operation along 'Course.users' will not proceed:sqlalchemy.exc.SAWarning
    ignore:Object of type <User> not in session, add operation along 'College.users' will not proceed:sqlalchemy.exc.SAWarning
    ignore:Object of type <User> not in session, add operation along 'School.users' will not proceed:sqlalchemy.exc.SAWarning