# Generated by Django 5.0.2 on 2024-02-21 19:10

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("embedding", pgvector.django.VectorField(dimensions=1024)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    pgvector.django.HnswIndex(
                        ef_construction=200,
                        fields=["embedding"],
                        m=16,
                        name="question_embedding_index",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
