# Generated by Django 5.0.3 on 2024-03-14 09:49

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
