# Generated by Django 5.0.3 on 2024-03-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_quiz_options_alter_question_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "essay topics",
            },
        ),
        migrations.CreateModel(
            name="Essay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="essays/files/")),
                ("extracted_text1", models.TextField(blank=True, null=True)),
                ("extracted_text2", models.TextField(blank=True, null=True)),
                ("cleaned_text", models.TextField(blank=True, null=True)),
                ("user_corrected_text", models.TextField(blank=True, null=True)),
                ("feedback1", models.TextField(blank=True, null=True)),
                ("feedback2", models.TextField(blank=True, null=True)),
                ("feedback3", models.TextField(blank=True, null=True)),
                ("feedback4", models.TextField(blank=True, null=True)),
                ("feedback5", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essays",
                        to="core.essaytopic",
                    ),
                ),
            ],
        ),
    ]
