# Generated by Django 5.0.3 on 2024-03-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_essay_author_essay_grade1_essay_grade2_essay_grade3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="query",
            field=models.TextField(blank=True, default=""),
        ),
    ]
