# Generated by Django 5.0.3 on 2024-03-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_extra_embedding_text_and_more'),
        ('core', '0008_alter_question_answer_text_alter_question_source_and_more'),
    ]

    operations = [
    ]
