# Generated by Django 5.0.3 on 2024-04-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userquizanswer_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='unique_query_subject',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='subject',
            new_name='area',
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('query', 'area'), name='unique_query_area'),
        ),
    ]
