# Generated by Django 5.0.4 on 2024-05-09 09:47

import django.db.models.deletion
from django.db import migrations, models


def set_user_quiz_answer_user_quiz(apps, schema_editor):
    UserQuizAnswer = apps.get_model("core", "UserQuizAnswer")
    UserQuiz = apps.get_model("core", "UserQuiz")

    to_update = []

    for user_quiz_answer in UserQuizAnswer.objects.all():
        user_quiz_answer.user_quiz, _ = UserQuiz.objects.get_or_create(
            quiz_id=user_quiz_answer.quiz_id,
            user_id=user_quiz_answer.user_id,
            defaults={"start_time": user_quiz_answer.timestamp},
        )
        to_update.append(user_quiz_answer)

    UserQuizAnswer.objects.bulk_update(to_update, ["user_quiz"])


def set_user_quiz_answered_questions(apps, schema_editor):
    UserQuiz = apps.get_model("core", "UserQuiz")
    UserQuizAnswer = apps.get_model("core", "UserQuizAnswer")

    for user_quiz in UserQuiz.objects.all():
        answered_questions = UserQuizAnswer.objects.filter(
            user_quiz=user_quiz
        ).values_list("question", flat=True)
        user_quiz.answered_questions.set(answered_questions)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_quiz_users"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userquizanswer",
            name="unique_user_quiz_question",
        ),
        migrations.AddField(
            model_name="userquiz",
            name="answered_questions",
            field=models.ManyToManyField(
                related_name="user_quiz_set",
                through="core.UserQuizAnswer",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="userquizanswer",
            name="user_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.userquiz",
                null=True,
            ),
        ),
        migrations.RunPython(set_user_quiz_answer_user_quiz),
        migrations.RunPython(set_user_quiz_answered_questions),
        migrations.AddConstraint(
            model_name="userquizanswer",
            constraint=models.UniqueConstraint(
                fields=("user_quiz", "question"), name="unique_user_quiz_question"
            ),
        ),
    ]
