# Generated by Django 5.0.4 on 2024-05-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_userquizanswer_unique_user_quiz_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquizanswer",
            name="user_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.userquiz",
            ),
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="user",
        ),
    ]
