# Generated by Django 5.0.6 on 2024-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240509_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/files/'),
        ),
    ]
