# Generated by Django 5.0.6 on 2024-06-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_essay_essay_topic"),
        ("api", "0016_alter_message_essay_topic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EssayTopic",
        ),
    ]
