# Generated by Django 5.0.6 on 2024-06-11 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_essay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(related_name='+', through='core.UserQuiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
