# Generated by Django 5.0.6 on 2024-06-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_quiz_users_alter_userquiz_user"),
        ("api", "0017_alter_message_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquizanswer",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="answered_questions",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="users",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="user_quiz",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="UserQuiz",
        ),
        migrations.DeleteModel(
            name="UserQuizAnswer",
        ),
    ]
