# Generated by Django 5.1.2 on 2024-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0004_challenge_questions_per_day_challenge_scoring_system'),
        ('quiz', '0026_remove_quiz_for_user_quiz_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('multiplier', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('challenges', models.ManyToManyField(to='challenges.challenge')),
                ('quizzes', models.ManyToManyField(to='quiz.quiz')),
            ],
        ),
    ]
