# Generated by Django 5.1.2 on 2024-12-12 02:27

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ("bonus_events", "0002_alter_bonusevent_challenges_alter_bonusevent_quizzes"),
        ("quiz", "0029_add_session_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonusevent",
            name="sessions",
            field=models.ManyToManyField(blank=True, to="quiz.session"),
        ),
    ]
