# Generated by Django 5.0.8 on 2024-08-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_userinfo_score_userinfo_humanities_score_and_more'),
        ('quiz', '0013_question_parameter_a_question_parameter_b_and_more'),
    ]

    operations = [
    ]
