# Generated by Django 5.1 on 2024-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_question_allow_resubmit_question_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choices'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('image__isnull', True), _negated=True), models.Q(('image', ''), _negated=True), ('text__exact', '')), models.Q(models.Q(('image__isnull', True), ('image', ''), _connector='OR'), models.Q(('text__exact', ''), _negated=True)), _connector='OR'), name='choice_has_image_xor_text'),
        ),
    ]
