# Generated by Django 5.1.2 on 2024-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0026_remove_quiz_for_user_quiz_created_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userquizanswer",
            name="choice_xor_text",
        ),
        migrations.RenameField(
            model_name="userquizanswer",
            old_name="text",
            new_name="submitted_text",
        ),
        migrations.AddField(
            model_name="userquizanswer",
            name="grade",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userquizanswer",
            name="feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="userquizanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("choice__isnull", True), _negated=True),
                        ("submitted_text__exact", ""),
                    ),
                    models.Q(
                        ("choice__isnull", True),
                        models.Q(("submitted_text__exact", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="choice_xor_submitted_text",
            ),
        ),
    ]
