# Generated by Django 5.1.2 on 2024-12-17 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0030_migrate_quiz_data"),
    ]

    operations = [
        # remove the constraints before removing the fields
        migrations.RemoveConstraint(
            model_name="userquiz",
            name="new_unique_user_quiz",
        ),
        migrations.RemoveConstraint(
            model_name="userquizanswer",
            name="new_unique_user_quiz_question",
        ),
        migrations.RemoveConstraint(
            model_name="userquizanswer",
            name="choice_xor_submitted_text",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="answered_questions",
        ),
        migrations.RemoveField(
            model_name="userquiz",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="user_quiz",
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="userquizanswer",
            name="question",
        ),
    ]
