# Generated by Django 5.1.2 on 2024-12-30 16:05

from django.conf import settings
from django.db import migrations, models


def migrate_rounds_fields(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(session_type="duel").update(
        n_rounds=3, n_questions_per_round=10
    )


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0037_remove_session_quiz_must_have_valid_quiz_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="non_duel_must_not_have_selection_method",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="duel_selection_method_must_be_valid",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="quiz_must_have_valid_question_type",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="quiz_must_have_valid_quiz_type",
        ),
        migrations.AddField(
            model_name="session",
            name="n_questions_per_round",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="n_rounds",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_rounds_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("question_type__in", ("multiple_choice", "open_ended", "all")),
                        ("quiz_type__in", ("query", "personalized", "custom")),
                        ("session_type", "quiz"),
                    ),
                    models.Q(("session_type", "quiz"), _negated=True),
                    _connector="OR",
                ),
                name="quiz_must_have_valid_types",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("n_questions_per_round__isnull", False),
                        ("n_rounds__isnull", False),
                        (
                            "selection_method__in",
                            ("random_official", "query_official", "user_generated"),
                        ),
                        ("session_type", "duel"),
                    ),
                    models.Q(
                        models.Q(("session_type", "duel"), _negated=True),
                        ("n_questions_per_round__isnull", True),
                        ("n_rounds__isnull", True),
                        ("selection_method", ""),
                    ),
                    _connector="OR",
                ),
                name="duel_fields_must_be_set_and_valid_if_duel",
            ),
        ),
    ]
