# Generated by Django 5.1.2 on 2024-12-30 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "quiz",
            "0038_remove_session_non_duel_must_not_have_selection_method_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            SELECT SETVAL(
                pg_get_serial_sequence('quiz_session', 'id'),
                (SELECT MAX(id) FROM quiz_session) + 1
            );
            """,
            reverse_sql="""
            SELECT SETVAL(
                pg_get_serial_sequence('quiz_session', 'id'),
                (SELECT MAX(id) FROM quiz_session) + 1
            );
            """,
        ),
    ]
