# Generated by Django 5.1.5 on 2025-01-22 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_sessionquestionuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionquestionuser',
            name='session_question_answer_valid_states',
        ),
        migrations.AlterField(
            model_name='sessionquestionuser',
            name='session_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_question_user_set', to='quiz.sessionquestion'),
        ),
        migrations.AlterField(
            model_name='sessionquestionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_question_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sessionquestionuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('choice__isnull', False), ('submitted_text__exact', ''), ('timed_out', False)), models.Q(('choice__isnull', True), models.Q(('submitted_text__exact', ''), _negated=True), ('timed_out', False)), models.Q(('choice__isnull', True), ('submitted_text__exact', '')), _connector='OR'), name='session_question_user_valid_states'),
        ),
    ]
