# Generated by Django 5.1.5 on 2025-01-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0056_sessionparticipation_duel_score_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_fast',
            field=models.BooleanField(default=True),
        ),
    ]
