# Generated by Django 5.0.6 on 2024-06-11 21:33

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0026_delete_essay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("extra_embedding_text", models.TextField(blank=True, default="")),
                ("text", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions"),
                ),
                ("answer_text", models.TextField(blank=True, default="")),
                (
                    "answer_image",
                    models.ImageField(blank=True, null=True, upload_to="answers"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1024, null=True),
                ),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    pgvector.django.HnswIndex(
                        ef_construction=200,
                        fields=["embedding"],
                        m=16,
                        name="new_question_embedding_index",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "order_with_respect_to": "question",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query", models.TextField(blank=True, default="")),
                ("area", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_filter",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="quizzes/files/"),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text=None, related_name="quizzes", to="quiz.question"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="UserQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_quiz_set",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_quiz_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="users",
            field=models.ManyToManyField(
                related_name="quizzes",
                through="quiz.UserQuiz",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserQuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_quiz_answer_set",
                        to="quiz.choice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_quiz_answer_set",
                        to="quiz.question",
                    ),
                ),
                (
                    "user_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_quiz_answer_set",
                        to="quiz.userquiz",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userquiz",
            name="answered_questions",
            field=models.ManyToManyField(
                related_name="user_quiz_set",
                through="quiz.UserQuizAnswer",
                to="quiz.question",
            ),
        ),
        migrations.AddConstraint(
            model_name="userquizanswer",
            constraint=models.UniqueConstraint(
                fields=("user_quiz", "question"), name="new_unique_user_quiz_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="userquiz",
            constraint=models.UniqueConstraint(
                fields=("user", "quiz"), name="new_unique_user_quiz"
            ),
        ),
    ]
