# Generated by Django 5.0.6 on 2024-06-12 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_auto_20240612_0640"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO quiz_quiz_questions (
                id,
                quiz_id,
                question_id
            )
            SELECT
                id,
                quiz_id,
                question_id
            FROM
                core_quiz_questions;
            SELECT setval(pg_get_serial_sequence('"quiz_quiz_questions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "quiz_quiz_questions";
            """,
            reverse_sql="""
            INSERT INTO core_quiz_questions (
                id,
                quiz_id,
                question_id
            )
            SELECT
                id,
                quiz_id,
                question_id
            FROM
                quiz_quiz_questions;
            SELECT setval(pg_get_serial_sequence('"core_quiz_questions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_quiz_questions";
            """,
        ),
    ]
