# Generated by Django 5.0.6 on 2024-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20240612_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='caderno',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='caderno_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
