# Generated by Django 5.0.6 on 2024-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
