# Generated by Django 5.0.7 on 2024-07-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
