# Generated by Django 5.0.7 on 2024-08-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question_category_question_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parameter_A',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='parameter_B',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='parameter_C',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
