# Generated by Django 5.0.8 on 2024-08-08 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_merge_20240807_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('query', ''), _negated=True), models.Q(('query__isnull', True), _negated=True)), fields=('area', 'source_filter', 'query'), name='unique_area_source_query'),
        ),
    ]
