# Generated by Django 5.1 on 2024-08-16 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quiz_unique_area_source_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='unique_area_source_query',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('open_ended', 'Open-ended'), ('all', 'All')], default='all', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('query', ''), _negated=True), models.Q(('query__isnull', True), _negated=True)), fields=('area', 'source_filter', 'query', 'question_type'), name='unique_area_source_query_question_type'),
        ),
    ]
