# Generated by Django 5.1.1 on 2024-09-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_remove_quiz_unique_area_source_query_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='parent_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_quizzes', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('query', 'Query-based'), ('personalized', 'Personalized')], default='query', max_length=16),
        ),
    ]
