# Generated by Django 5.1.1 on 2024-09-30 17:58

import random
import string

from django.db import migrations, models


def generate_random_code(length=5):
    chars = string.ascii_uppercase + string.digits  # Base 36 (A-Z, 0-9)
    return "".join(random.choice(chars) for _ in range(length))


def add_codes_to_quizzes(apps, schema_editor):
    Quiz = apps.get_model("quiz", "Quiz")
    CODE_GENERATION_MAX_RETRIES = 10  # Define max retries for generating unique code
    assigned_codes = set()

    # Collect any existing codes from the database, just in case
    existing_codes = set(
        Quiz.objects.exclude(code__isnull=True).values_list("code", flat=True)
    )
    assigned_codes.update(existing_codes)

    for quiz in Quiz.objects.all():
        for attempt in range(CODE_GENERATION_MAX_RETRIES):
            code = generate_random_code()
            if code in assigned_codes:
                continue  # Code already assigned, try again
            assigned_codes.add(code)
            quiz.code = code
            quiz.save(update_fields=["code"])
            break
        else:
            # If unable to generate a unique code after max retries
            raise ValueError(
                f"Unable to generate a unique code for quiz ID {quiz.id} after multiple attempts"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0022_quiz_parent_quiz_quiz_quiz_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="code",
            field=models.CharField(
                max_length=5, null=True
            ),  # Allow null values temporarily
        ),
        migrations.RunPython(
            add_codes_to_quizzes, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="quiz",
            name="code",
            field=models.CharField(
                max_length=5, unique=True
            ),  # Make it unique and non-nullable now
        ),
    ]
