# Generated by Django 5.1.2 on 2024-10-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizanswer',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userquizanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_answer_set', to='quiz.choice'),
        ),
        migrations.AddConstraint(
            model_name='userquizanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('choice__isnull', True), _negated=True), ('text__exact', '')), models.Q(('choice__isnull', True), models.Q(('text__exact', ''), _negated=True)), _connector='OR'), name='choice_xor_text'),
        ),
    ]
