# Generated by Django 5.1.2 on 2024-10-19 13:56

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0025_userquizanswer_text_alter_userquizanswer_choice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="for_user",
            new_name="created_by",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(api.models.get_deleted_user),
                related_name="quizzes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
