# Generated by Django 5.1.2 on 2024-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_remove_userquizanswer_choice_xor_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('open_ended', 'Open-ended'), ('all', 'All')], default='multiple_choice', max_length=16),
        ),
    ]
