# Generated by Django 5.1.2 on 2024-12-17 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0031_remove_userquiz_quiz_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="UserQuiz",
        ),
        migrations.DeleteModel(
            name="UserQuizAnswer",
        ),
    ]
