# Generated by Django 5.1.2 on 2024-12-24 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.session',),
        ),
        migrations.AddField(
            model_name='session',
            name='selection_method',
            field=models.CharField(blank=True, choices=[('random_official', 'Random official'), ('query_official', 'Query official'), ('user_generated', 'User-generated'), ('', 'Not applicable')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='question_type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'Multiple choice'), ('open_ended', 'Open-ended'), ('all', 'All'), ('', 'Not applicable')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='session',
            name='quiz_type',
            field=models.CharField(blank=True, choices=[('query', 'Query-based'), ('personalized', 'Personalized'), ('', 'Not applicable')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(related_name='sessions', through='quiz.SessionParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_session_user_participant'),
        ),
    ]
