# Generated by Django 5.1.2 on 2024-12-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0034_duel_session_selection_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SessionParticipant",
            new_name="SessionParticipation",
        ),
        migrations.AlterField(
            model_name="sessionparticipation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_participation_set",
                to="quiz.session",
            ),
        ),
        migrations.AlterField(
            model_name="sessionparticipation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_participation_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
