# Generated by Django 5.1.2 on 2025-01-01 00:23

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0039_auto_20241230_1515"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="current_turn_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(api.models.get_deleted_user),
                related_name="sessions_current_turn_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="duel_phase",
            field=models.CharField(
                choices=[
                    ("", "Not applicable"),
                    ("attack", "Attack"),
                    ("defense", "Defense"),
                ],
                default="",
                max_length=25,
            ),
        ),
    ]
