# Generated by Django 5.1.2 on 2025-01-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0041_auto_20241231_2130"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="duel_fields_must_be_set_and_valid_if_duel",
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_turn_user__isnull", False),
                        ("duel_phase__in", ("attack", "defense")),
                        ("n_questions_per_round__isnull", False),
                        ("n_rounds__isnull", False),
                        (
                            "selection_method__in",
                            ("random_official", "query_official", "user_generated"),
                        ),
                        ("session_type", "duel"),
                    ),
                    models.Q(
                        models.Q(("session_type", "duel"), _negated=True),
                        ("current_turn_user__isnull", True),
                        ("duel_phase", ""),
                        ("n_questions_per_round__isnull", True),
                        ("n_rounds__isnull", True),
                        ("selection_method", ""),
                    ),
                    _connector="OR",
                ),
                name="duel_fields_must_be_set_and_valid_if_duel",
            ),
        ),
    ]
