# Generated by Django 5.1.2 on 2025-01-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20241231_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='session',
            name='duel_phase',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('attack', 'Attack'), ('defense', 'Defense')], default='', max_length=25),
        ),
    ]
