# Generated by Django 5.1.2 on 2025-01-09 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_remove_sessionquestionanswer_session_question_answer_choice_xor_submitted_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='duel_fields_must_be_set_and_valid_if_duel',
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_turn_start_time__isnull', False), ('duel_phase__in', ('attack', 'defense')), ('duel_status__in', ('in_progress', 'completed', 'abandoned')), ('n_questions_per_round__isnull', False), ('n_rounds__isnull', False), ('selection_method__in', ('random_official', 'query_official', 'user_generated')), ('session_type', 'duel')), models.Q(models.Q(('session_type', 'duel'), _negated=True), ('current_turn_start_time__isnull', True), ('current_turn_user__isnull', True), ('duel_phase', ''), ('duel_status', ''), ('n_questions_per_round__isnull', True), ('n_rounds__isnull', True), ('selection_method', ''), ('winner__isnull', True)), _connector='OR'), name='duel_fields_must_be_set_and_valid_if_duel'),
        ),
    ]
