# Generated by Django 5.1.5 on 2025-01-22 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "quiz",
            "0048_remove_session_duel_fields_must_be_set_and_valid_if_duel_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessionquestionanswer",
            name="session_question_answer_choice_xor_submitted_text",
        ),
        migrations.AddField(
            model_name="sessionquestionanswer",
            name="timed_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="sessionquestionanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("choice__isnull", False),
                        ("submitted_text__exact", ""),
                        ("timed_out", False),
                    ),
                    models.Q(
                        ("choice__isnull", True),
                        models.Q(("submitted_text__exact", ""), _negated=True),
                        ("timed_out", False),
                    ),
                    models.Q(("choice__isnull", True), ("submitted_text__exact", "")),
                    _connector="OR",
                ),
                name="session_question_answer_valid_states",
            ),
        ),
    ]
