# Generated by Django 5.1.5 on 2025-01-25 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_merge_20250122_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, default='')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.duel')),
            ],
            options={
                'order_with_respect_to': 'duel',
            },
        ),
    ]
