# Generated by Django 5.1.5 on 2025-01-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0055_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipation',
            name='duel_score_change',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
