# Generated by Django 5.1.5 on 2025-02-05 18:23

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_tournament_tournamentparticipation_and_more"),
        ("quiz", "0059_challenge_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[("attack", "Attack"), ("defense", "Defense")],
                        max_length=25,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="quiz_must_have_valid_types",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="duel_fields_must_be_set_and_valid_if_duel",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="challenge_or_duel_fields_must_be_set",
        ),
        migrations.RemoveConstraint(
            model_name="session",
            name="challenge_start_and_end_time_must_be_set",
        ),
        migrations.RemoveField(
            model_name="session",
            name="current_turn_start_time",
        ),
        migrations.RemoveField(
            model_name="session",
            name="current_turn_user",
        ),
        migrations.RemoveField(
            model_name="session",
            name="duel_phase",
        ),
        migrations.RemoveField(
            model_name="session",
            name="n_rounds",
        ),
        migrations.AddField(
            model_name="turn",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.round"
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(api.models.get_deleted_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="users",
            field=models.ManyToManyField(
                through="quiz.Turn", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="current_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(api.models.get_deleted_user),
                related_name="sessions",
                to="quiz.turn",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("question_type__in", ("multiple_choice", "open_ended", "all")),
                        ("session_type", "quiz"),
                    ),
                    models.Q(("session_type", "quiz"), _negated=True),
                    _connector="OR",
                ),
                name="quiz_question_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("quiz_type__in", ("query", "personalized", "custom")),
                        ("session_type", "quiz"),
                    ),
                    models.Q(("session_type", "quiz"), _negated=True),
                    _connector="OR",
                ),
                name="quiz_quiz_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("duel_status__in", ("in_progress", "completed", "abandoned")),
                        ("n_questions_per_round__isnull", False),
                        ("session_type", "duel"),
                    ),
                    models.Q(("session_type", "duel"), _negated=True),
                    _connector="OR",
                ),
                name="duel_required_fields_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("session_type", "duel"), _negated=True),
                        ("current_turn__isnull", True),
                        ("duel_status", ""),
                        ("n_questions_per_round__isnull", True),
                        ("tournament__isnull", True),
                        ("winner__isnull", True),
                    ),
                    ("session_type", "duel"),
                    _connector="OR",
                ),
                name="duel_non_applicable_fields_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "selection_method__in",
                            ("random_official", "query_official", "user_generated"),
                        ),
                        ("session_type__in", ["duel", "challenge"]),
                    ),
                    models.Q(
                        ("session_type__in", ["duel", "challenge"]), _negated=True
                    ),
                    _connector="OR",
                ),
                name="duel_challenge_selection_method_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("session_type__in", ["duel", "challenge"]), _negated=True
                        ),
                        ("selection_method", ""),
                    ),
                    ("session_type__in", ["duel", "challenge"]),
                    _connector="OR",
                ),
                name="non_duel_challenge_selection_method_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("end_time__isnull", False),
                        ("session_type", "challenge"),
                        ("start_time__isnull", False),
                    ),
                    models.Q(("session_type", "challenge"), _negated=True),
                    _connector="OR",
                ),
                name="challenge_start_end_time_valid",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="turn",
            order_with_respect_to="round",
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                fields=("round", "user"), name="unique_turn_per_round_and_user"
            ),
        ),
    ]
