# Generated by Django 5.2 on 2025-05-09 10:16

from django.db import migrations
from django.db.models import F


def add_titles(apps, schema_editor):
    Session = apps.get_model("quiz", "Session")
    Session.objects.filter(title="").update(title=F("query"))


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0065_remove_session_duel_challenge_selection_method_valid_and_more"),
    ]

    operations = [
        migrations.RunPython(add_titles, migrations.RunPython.noop),
    ]
