# Generated by Django 5.1.1 on 2024-09-26 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['user', 'challenge'], name='challenges__user_id_342380_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipation',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_participation'),
        ),
    ]
