# Generated by Django 5.1.1 on 2024-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengeparticipation_challenges__user_id_342380_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='unnamed', max_length=255),
            preserve_default=False,
        ),
    ]
