# Generated by Django 5.1.2 on 2024-10-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='questions_per_day',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='scoring_system',
            field=models.CharField(choices=[('frequency', 'Frequency'), ('quantity', 'Quantity')], default='frequency', max_length=12),
            preserve_default=False,
        ),
    ]
