# Generated by Django 5.0.6 on 2024-06-11 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("essays", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
    INSERT INTO essays_essaytopic (
        id,
        name,
        created_at
    )
    SELECT
        id,
        name,
        created_at
    FROM
        core_essaytopic;
    SELECT setval(pg_get_serial_sequence('"essays_essaytopic"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "essays_essaytopic";
    """,
            reverse_sql="""
    INSERT INTO core_essaytopic (
        id,
        name,
        created_at
    )
    SELECT
        id,
        name,
        created_at
    FROM
        essays_essaytopic;
    SELECT setval(pg_get_serial_sequence('"core_essaytopic"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_essaytopic";
    """,
        ),
    ]
