# Generated by Django 5.1.6 on 2025-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_essaytype_extractedtext_feedback_feedbackcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='original_file',
            field=models.FileField(blank=True, default='', upload_to='essays/files/'),
            preserve_default=False,
        ),
    ]
