# Generated by Django 5.0.2 on 2024-02-16 03:03

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_is_premium"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name="embeddedtextchunk",
            name="attachment_message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="message",
            name="file_processing_done",
        ),
        migrations.AlterField(
            model_name="embeddedtextchunk",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="EmbeddedFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(upload_to=api.models.file_upload_directory_path),
                ),
                (
                    "file_processing_done",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "messages",
                    models.ManyToManyField(
                        blank=True, related_name="embedded_files", to="api.message"
                    ),
                ),
                (
                    "file_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedded_files",
                        to="api.filegroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="embeddedtextchunk",
            name="embedded_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedded_text_chunks",
                to="api.embeddedfile",
            ),
            preserve_default=False,
        ),
    ]
