# Generated by Django 5.0.3 on 2024-03-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_0006_chatroom_icon_0006_message_essay_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
