# Generated by Django 5.0.3 on 2024-04-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_membership_unique_together_and_more'),
        ('core', '0011_userquizanswer_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.quiz'),
        ),
    ]
