# Generated by Django 5.0.4 on 2024-04-29 20:54

from django.db import migrations, models


def forward_chat_type(apps, schema_editor):
    Chatroom = apps.get_model("api", "Chatroom")
    updated_chatrooms = []

    for chatroom in Chatroom.objects.all():
        if chatroom.chat_type == 0:
            chatroom.temp_chat_type = "GP"  # Group
        elif chatroom.chat_type == 1:
            chatroom.temp_chat_type = "DM"  # Direct Message
        elif chatroom.chat_type == 2:
            chatroom.temp_chat_type = "OF"  # Official
        updated_chatrooms.append(chatroom)

    # Perform a bulk update
    Chatroom.objects.bulk_update(updated_chatrooms, ["temp_chat_type"])


def forward_role(apps, schema_editor):
    Membership = apps.get_model("api", "Membership")
    updated_memberships = []
    for member in Membership.objects.all():
        if member.role == 0:
            member.temp_role = "MEM"  # Member
        elif member.role == 1:
            member.temp_role = "ADM"  # Admin
        elif member.role == 2:
            member.temp_role = "CRE"  # Creator
        updated_memberships.append(member)

    # Perform a bulk update
    Membership.objects.bulk_update(updated_memberships, ["temp_role"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_chatroom_is_official_chatroom_chat_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DMChatroom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.chatroom",),
        ),
        migrations.CreateModel(
            name="GroupChatroom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.chatroom",),
        ),
        migrations.CreateModel(
            name="OfficialChatroom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.chatroom",),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="temp_chat_type",
            field=models.CharField(
                max_length=2,
                choices=[("DM", "Direct Message"), ("GP", "Group"), ("OF", "Official")],
                default="GP",
            ),
        ),
        migrations.RunPython(forward_chat_type),
        migrations.RemoveField(
            model_name="chatroom",
            name="chat_type",
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="temp_chat_type",
            new_name="chat_type",
        ),
        migrations.AddField(
            model_name="membership",
            name="temp_role",
            field=models.CharField(
                max_length=3,
                choices=[("MEM", "Member"), ("ADM", "Admin"), ("CRE", "Creator")],
                default="MEM",
            ),
        ),
        migrations.RunPython(forward_role),
        migrations.RemoveField(
            model_name="membership",
            name="role",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="temp_role",
            new_name="role",
        ),
    ]
