# Generated by Django 5.0.4 on 2024-05-02 22:09

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dmchatroom_groupchatroom_officialchatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET(api.models.UserManager.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
