# Generated by Django 5.0.6 on 2024-05-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
