# Generated by Django 5.0.6 on 2024-07-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_message_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('user_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('user_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.college'),
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(to='api.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
    ]
