# Generated by Django 5.1 on 2024-09-02 09:37

import api.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_college_course_user_chosen_college_college_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.models.user.get_deleted_user), related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
