# Generated by Django 5.1 on 2024-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_user_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="commitment",
            field=models.IntegerField(default=20),
        ),
    ]
