# Generated by Django 5.1.1 on 2024-10-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_message_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[(None, 'Unknown'), ('MS', 'Middle School'), ('FYHS', 'First Year High School'), ('SYHS', 'Second Year High School'), ('TYHS', 'Third Year High School'), ('HSG', 'High School Complete'), ('COL', 'College')], default='', max_length=4),
        ),
    ]
