# Generated by Django 5.1.2 on 2024-12-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_message_quiz_message_session"),
        ("quiz", "0030_migrate_quiz_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="quiz",
        ),
        migrations.AlterField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MS", "Middle School"),
                    ("FYHS", "First Year High School"),
                    ("SYHS", "Second Year High School"),
                    ("TYHS", "Third Year High School"),
                    ("HSG", "High School Complete"),
                    ("COL", "College"),
                    ("", "Unknown"),
                ],
                default="",
                max_length=4,
            ),
        ),
    ]
