# Generated by Django 5.1.6 on 2025-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_school_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to='chatroom_icons'),
            preserve_default=False,
        ),
    ]
