# Generated by Django 5.1.5 on 2025-01-24 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserLastConnection",
            new_name="UserWebsocketInfo",
        ),
    ]
