# Generated by Django 5.1.5 on 2025-01-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userwebsocketinfo_delete_userlastconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsocketinfo',
            name='last_websocket_disconnection',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userwebsocketinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
