# Generated by Django 5.1.4 on 2025-01-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='valid_currency_category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='currency',
            name='category',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('essay', 'Essay'), ('duel', 'Duel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='currency.currency'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['quiz', 'essay', 'duel'])), name='valid_currency_category'),
        ),
    ]
