# Generated by Django 5.1.4 on 2025-01-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currency_valid_currency_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='amount',
            new_name='value',
        ),
    ]
