# Generated by Django 5.1.5 on 2025-03-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('currency', '0004_remove_currency_valid_currency_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='unique_default_currency_per_category_type',
        ),
        migrations.RemoveConstraint(
            model_name='currency',
            name='valid_currency_category',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='category',
        ),
        migrations.AddField(
            model_name='currency',
            name='action',
            field=models.CharField(choices=[('quiz_creation', 'Quiz Creation'), ('quiz_join', 'Quiz Join'), ('duel_creation', 'Duel Creation'), ('duel_join', 'Duel Join'), ('essay_creation', 'Essay Creation'), ('challenge_creation', 'Challenge Creation'), ('challenge_join', 'Challenge Join'), ('challenge_redeem', 'Challenge Redeem')], default='quiz_creation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('action', 'currency_type', 'is_default'), name='unique_default_currency_per_action_type'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['quiz_creation', 'quiz_join', 'duel_creation', 'duel_join', 'essay_creation', 'challenge_creation', 'challenge_join', 'challenge_redeem'])), name='valid_currency_action'),
        ),
    ]
