# Generated by Django 5.1.5 on 2025-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('currency', '0006_remove_currency_valid_currency_action_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='valid_currency_action',
        ),
        migrations.AlterField(
            model_name='currency',
            name='action',
            field=models.CharField(choices=[('custom_quiz_creation', 'Custom Quiz Creation'), ('custom_quiz_join', 'Custom Quiz Join'), ('quiz_creation', 'Quiz Creation'), ('quiz_join', 'Quiz Join'), ('custom_duel_creation', 'Custom Duel Creation'), ('custom_duel_join', 'Custom Duel Join'), ('duel_creation', 'Duel Creation'), ('duel_join', 'Duel Join'), ('essay_creation', 'Essay Creation'), ('custom_challenge_creation', 'Custom Challenge Creation'), ('custom_challenge_join', 'Custom Challenge Join'), ('custom_challenge_commission', 'Custom Challenge Commission'), ('challenge_creation', 'Challenge Creation'), ('challenge_join', 'Challenge Join'), ('challenge_commission', 'Challenge Commission')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['custom_quiz_creation', 'custom_quiz_join', 'quiz_creation', 'quiz_join', 'custom_duel_creation', 'custom_duel_join', 'duel_creation', 'duel_join', 'essay_creation', 'custom_challenge_creation', 'custom_challenge_join', 'custom_challenge_commission', 'challenge_creation', 'challenge_join', 'challenge_commission'])), name='valid_currency_action'),
        ),
    ]
