# Generated by Django 5.1.6 on 2025-03-08 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_remove_currency_valid_currency_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
